### ISSUE TITLE
A strange error

### ISSUE THREAD

**Issue by EmosewaGamer** [BlakeBr0/ExtendedCrafting#1]
So, I was adding recipes for creative items with this mod and when I joined a world I got "Error executing creative.zs: 5". That didn't really give me any information to what the problem is, so now I'm asking you.
 The part of the CraftTweaker log where the issue happened: https://pastebin.com/f6yLGUZL
 The script for the recipe: https://pastebin.com/YvCzDyP0

**Comment by EmosewaGamer** [comment]
Well, I remove that recipe and I got error 4. Guessing thatremoving the next recipe will give me error 3 and so on, here's the full script: https://pastebin.com/7xyG4ZVZ

**Comment by BlakeBr0** [comment]
Im pretty sure the issue is that your rows arent the same length, since your first row seems to have 5 items and the next one has 6 etc.

**Comment by EmosewaGamer** [comment]
That's not an issue with regular crafting recipes. Can't you make that not be an issue?
