### ISSUE TITLE
Interface possibly now working

### ISSUE THREAD

**Issue by EmosewaGamer** [BlakeBr0/ExtendedCrafting#10]
So I have set an Ultimate Crafting Table recipe, but the Automation Interface is doing absolutely nothing 
![image](https://user-images.githubusercontent.com/25333164/32404733-2691d062-c156-11e7-889f-8e533126bf60.png)
![image](https://user-images.githubusercontent.com/25333164/32404734-2a005f02-c156-11e7-9a55-f9f180332fa0.png)

 And a question that I have is: What's the RF bar for? If it requires RF to run, the issue is that isn't accepting power.
![image](https://user-images.githubusercontent.com/25333164/32404745-9d487a12-c156-11e7-8d29-55623337d793.png)

**Comment by BlakeBr0** [comment]
Submitted a new version that should fix this
