### ISSUE TITLE
[1.15.2] Crafting core and pedestral don't work with datapack recipe

### ISSUE THREAD

**Issue by AlleCraft** [BlakeBr0/ExtendedCrafting#100]
Crafting core and pedestral don't work with datapack recipe, but can view recipe with jei...
![2020-06-09-16-57-11](https://user-images.githubusercontent.com/51967599/84164126-78eccd00-aa72-11ea-8df6-15aa69ca4871.gif)

**Comment by BlakeBr0** [comment]
Can I get the recipe json?

**Comment by AlleCraft** [comment]
[black_iron.txt](https://github.com/BlakeBr0/ExtendedCrafting/files/4776408/black_iron.txt)

I put it in a .txt file but in the datapack it is .json

**Comment by BlakeBr0** [comment]
Looks like the issue is actually that you can't have any empty pedestals.
