### ISSUE TITLE
[1.15.2] Extended Crafting makes people unable to join my LAN server (via Hamachi)

### ISSUE THREAD

**Issue by Spearkiller** [BlakeBr0/ExtendedCrafting#101]
Every now and again, my friends and I like to do playthroughs through Hamachi. I used this mod in 1.12.2 and everything worked fine. But ever since I introduced this mod into my 1.15.2 modpack, All my friends have been getting this exact same error: 

![image](https://user-images.githubusercontent.com/10781437/85405544-ae3a0480-b5b4-11ea-877b-3be8fbb8b81f.png)

They'll join for about a second and be quickly booted out. I have only found this exact error occurring with this mod. Ive never seen it happen when playing any other modpacks, or playing on a realm.

We've done extensive testing and have found it only happens with this mod, hence why I'm reporting it here. It could be a hamachi issue, but it worked in 1.12.2 so this is the best I've got.

**Comment by BlakeBr0** [comment]
Can I get logs?

**Comment by BlakeBr0** [comment]
Nvermind, I figured it out. I'll get a release out shortly.
