### ISSUE TITLE
Disabling Extended Crafting 

### ISSUE THREAD

**Issue by Sp00kiBoi** [BlakeBr0/ExtendedCrafting#102]
Extended Crafting was added to a modpack that i have been playing on recently. i was wondering if there is a way to revert it back from the new crafting recipes to the original recipes from the modpack as disabling or removing the mod removes all crafting recipes in their entirety. i cannot use an older version of the modpack.
Any help would be appreciated. thanks

**Comment by BlakeBr0** [comment]
This is an issue tracker, not a support forum. You'll have to talk to the creator of the modpack if you want help. 

That being said though if you want to remove the mod  you'll have to look through the modpacks crafttweaker scripts and remove anything that has to do with extendedcrafting, as well as anywhere they would be removing the recipes.
