### ISSUE TITLE
Issues with Singularities

### ISSUE THREAD

**Issue by dmich9** [BlakeBr0/ExtendedCrafting#103]
Hey, so I've added a ton of cutom singularities through extended crafting's config file. However, nothing I seem to do can make the game boot up properly. 
I've pasted my configuration file here (yes, all the singularity colors are random).

# Configuration file

##########################################################################################################
# automation_interface
#--------------------------------------------------------------------------------------------------------#
# Settings for the Automation Interface.
##########################################################################################################

automation_interface {
    # Should the Automation Interface be enabled? [default: true]
    B:enabled=true

    # How much FE the Automation Interface should hold. [range: 0 ~ 2147483647, default: 1000000]
    I:energy_capacity=1000000

    # How much FE the Automation Interface should use when moving items. [range: 0 ~ 100000, default: 80]
    I:energy_rate=80

    # Should the Automation Interface render the result item inside it? [default: true]
    B:render_item=true
}

##########################################################################################################
# combination_crafting
#--------------------------------------------------------------------------------------------------------#
# Settings for the Crafting Core.
##########################################################################################################

combination_crafting {
    # Should the Crafting Core and Pedestal be enabled? [default: true]
    B:enabled=true

    # How much FE the Crafting Core should hold. [range: 0 ~ 2147483647, default: 5000000]
    I:energy_capacity=5000000

    # How much FE/t the Crafting Core should use when crafting by default. [range: 0 ~ 2147483647, default: 500]
    I:energy_rate=500
}

##########################################################################################################
# ender_crafting
#--------------------------------------------------------------------------------------------------------#
# Settings for the Ender Crafter.
##########################################################################################################

ender_crafting {
    # How much an Ender Alternator should speed up a craft. This is the percentage of time_required. [range: 0.0 ~ 1.0, default: 0.01]
    S:alternator_effectiveness=0.01

    # Should the Ender Crafter and Ender Alternator be enabled? [default: true]
    B:enabled=true

    # How many seconds each craft should take. [range: 1 ~ 2147483647, default: 60]
    I:time_required=60
}

##########################################################################################################
# general
#--------------------------------------------------------------------------------------------------------#
# Settings for general things.
##########################################################################################################

general {
    # Should WAILA show the current energy of Extended Crafting machines? [default: true]
    B:energy_in_waila=true

    # Should the In-Game Guide Book be enabled? [default: true]
    B:guide_enabled=true

    # Should the Handheld Crafting Table be enabled? [default: true]
    B:handheld_table_enabled=true
}

##########################################################################################################
# quantum_compression
#--------------------------------------------------------------------------------------------------------#
# Settings for the Quantum Compressor.
##########################################################################################################

quantum_compression {
    # Should the Quantum Compressor be enabled? [default: true]
    B:enabled=true

    # How much FE the Quantum Compressor should hold. [range: 0 ~ 2147483647, default: 10000000]
    I:energy_capacity=10000000

    # How much FE/t the Quantum Compressor should use when crafting by default. [range: 0 ~ 2147483647, default: 5000]
    I:energy_rate=5000

    # Should the Quantum Compressor render the result item above it? [default: true]
    B:render_item=true
}

##########################################################################################################
# recipe_maker
#--------------------------------------------------------------------------------------------------------#
# Settings for the Recipe Maker.
##########################################################################################################

recipe_maker {
    # Should the Recipe Maker be enabled? [default: true]
    B:enabled=true

    # Should the Recipe Maker also copy the NBT of the ingredients? [default: false]
    B:use_nbt=false

    # Should the Recipe Maker use OreDictionary entries when applicable? [default: true]
    B:use_oredictionary=true
}

##########################################################################################################
# singularity
#--------------------------------------------------------------------------------------------------------#
# Settings for the Singularities.
##########################################################################################################

singularity {
    # Here you can add your own custom Singularities.
    # - Syntax: meta;name;material;color
    # - Example: 12;super_potato;minecraft:carrot;123456
    # - 'meta' must be different for each, and should not be changed.
    # - 'name' should be lower case with underscores for spaces. Singularity is added automatically.
    # - Example: 'lots_of_spaghetti' would show 'Lots Of Spaghetti Singularity'.
    # - 'material' is an item id or ore dictionary entry. This is for the generic crafting recipe.
    # - Note: if you plan on adding your own recipe with the CraftTweaker integration, put 'none'.
    # - Examples: 'minecraft:stone' for stone, 'ore:ingotIron' for the ore dictionary entry 'ingotIron'.
    # - Note: you can also specify meta for item ids, by adding them to the end of the item id.
    # - Example: minecraft:stone:3 for a meta of 3. Make the meta 32767 for wildcard value.
    # - 'color' the color of the singularity as a hex value. http://htmlcolorcodes.com/
    # - Example: 123456 would color it as whatever that color is.
    S:custom_singularities <
     	80;nether_quartz;minecraft:quartz;65F59B
	81;fluxed_electrum;redstonearsenal:storage:0;F565C3
	82;knightslime;tconstruct:ingots:3;AE49CB
	83;pigiron;tconstruct:ingots:4;0A50E5
	84;aluminum_brass;tconstruct:ingots:5;FFDADA
	85;electrical_steel;enderio:item_alloy_ingot:0;FF0000
	36;energetic_alloy;enderio:item_alloy_ingot:1;0C00FF
	37;vibrant_alloy;enderio:item_alloy_ingot:2;00FF1B
	38;dark_steel;enderio:item_alloy_ingot:6;6B7BFF
	39;soularium;enderio:item_alloy_ingot:7;16CE00
	40;end_steel;enderio:item_alloy_ingot:8;8A715E
	41;energetic_silver;enderio:item_alloy_endergy_ingot:5;C46924
	42;vivid_alloy;enderio:item_alloy_endergy_ingot:6;0C8900
	43;melodic_alloy;enderio:item_alloy_endergy_ingot:2;FFFDC9
	44;crystalline_alloy;enderio:item_alloy_endergy_ingot:1;000000
	45;pulsating_iron;enderio:item_alloy_ingot:5;F1F1F1
	46;thorium;nuclearcraft:ingot:3;AF886E
	47;boron;nuclearcraft:ingot:5;000000
	86;lithium;nuclearcraft:ingot:6;E504CD
	87;magnesium;nuclearcraft:ingot:7;4B9936
	88;graphite;nuclearcraft:ingot:8;E3E39C
	51;alumite;plustic:alumiteingot;A90000
	52;mirion;plustic:mirioningot;3E0886
	53;compressed_iron;pneumaticcraft:ingot_iron_compressed;8D8D8E
	54;abyssalnite;abyssalcraft:abyingot;E6E6EB
	55;dreadium;abyssalcraft:dreadiumingot;C3C3EE
	56;hop_graphite;immersiveengineering:material:19;CC7BE8
	57;red_alloy;projectred-core:resource_item:103;FFF4EB
	58;electrotine_alloy;projectred-core:resource_item:104;7CD6DF
	59;ironwood;twilightforest:ironwood_ingot;20CADB
	60;fiery;twilightforest:fiery_ingot;FF43FC
	61;steeleaf;twilightforest:steeleaf_ingot;6F0AA5
	62;knightmetal;twilightforest:knightmetal_ingot;CAD001
	63;draconium;draconicevolution:draconium_ingot;1EBEFF
	89;refined_obsidian;mekanism:ingot:0;FFFB00
	90;osmium;mekanism:ingot:1;FF9B00
	91;refined_glowstone;mekanism:ingot:3;B2FF00
	67;cyanite;bigreactors:ingotcyanite;FF5D80
	68;manasteel;botania:manaresource:0;016204
	69;elementium;botania:manaresource:7;623F01
	70;terrasteel;botania:manaresource:4;ECE189
	71;certus_quartz;appliedenergistics2:material:0;F1B43B
	72;fluix_crystal;appliedenergistics2:material:7;FF95F1
	73;aquamarine;astralsorcery:itemcraftingcomponent:0;CDFF95
	74;starmetal;astralsorcery:itemcraftingcomponent:1;D1FAFE
	75;impregnated_diamond;tombstone:crafting_ingredient:2;7B2FD1
	76;crystallized_amber;cyclicmagic:crystallized_amber;CD001F
	77;crystallized_obsidian;cyclicmagic:crystallized_obsidian;A7A1A2
	78;red_heart;bhc:red_heart;E5B75B
	79;modularium;modularmachinery:itemmodularium;E5B75B

    # The catalyst required for the default Singularity recipes. modid:itemid:metadata [default: extendedcrafting:material:11]
    S:default_catalyst=extendedcrafting:material:11

    # Should the default Singularity recipes be enabled? [default: true]
    B:default_recipes=true

    # Disable specific default singularities here.
    S:default_singularities <
        coal=true
        iron=true
        lapis_lazuli=true
        redstone=true
        glowstone=false
        gold=true
        diamond=true
        emerald=true
        aluminum=true
        copper=true
        tin=true
        bronze=true
        zinc=true
        brass=true
        silver=true
        lead=true
        steel=true
        nickel=true
        constantan=true
        electrum=true
        invar=true
        mithril=true
        tungsten=false
        titanium=true
        uranium=true
        chrome=false
        platinum=true
        iridium=true
        signalum=true
        lumium=true
        enderium=true
        ardite=true
        cobalt=true
        manyullyn=true
     >

    # Should the Singularities be enabled? [default: true]
    B:enabled=true

    # The amount of RF required to craft a Singularity, for the default recipes. [range: 0 ~ 2147483647, default: 5000000]
    I:energy_cost=5000000

    # The amount of materials required to create a Singularity, for the default recipes. [range: 1 ~ 2147483647, default: 10000]
    I:material_amount=10000

    # Should the default Ultimate Singularity recipe be enabled? [default: true]
    B:ultimate_singularity_recipe=true

    # Blacklist Singularities from being in the Ultimate Singularity crafting recipe.
    # - Syntax: singularityType;meta
    # - 'singularityType' can be 'default' or 'custom'.
    # - 'default' for the ones added by the mod by default, 'custom' being the ones defined in '_custom_singularities'.
    # - Example: custom;12
    S:ultimate_singularity_recipe_blacklist <
	default;4,
	default;30,
	default;33
     >
}

##########################################################################################################
# table_crafting
#--------------------------------------------------------------------------------------------------------#
# Settings for the Extended Crafting Tables.
##########################################################################################################

table_crafting {
    # Should the Extended Crafting Tables be enabled? [default: true]
    B:enabled=true

    # Should the Basic Crafting Table inherit normal crafting recipes? [default: true]
    B:inherit_vanilla_recipes=true
}

**Comment by BlakeBr0** [comment]
I would need the crash log to see what's going wrong.

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity.
