### ISSUE TITLE
This module has a bug with unlimited brush

### ISSUE THREAD

**Issue by lengshao233** [BlakeBr0/ExtendedCrafting#104]
Affected version: 1.12.2 CatServer side
Trigger process: will any workbench on the ground, it set the synthetic objects, not to be good synthetic goods out, close the GUI will automatically save the synthesis column items, put a funnel at the bottom of the workbench, synthesize synthetic within needs something, such as items after all is drawn, synthetic good window will be good things, and the material is already out, brush this bug can be infinite
Solution: Nothing found

**Comment by BlakeBr0** [comment]
This is a pretty poor translation but from what I can understand you're saying that there's a dupe involving pulling items out of the table with hoppers, which shouldn't be possible. Also worth noting that I am no longer maintaining the 1.12 version.
