### ISSUE TITLE
table recipes not working with craftweaker

### ISSUE THREAD

**Issue by TheNimbleNinja** [BlakeBr0/ExtendedCrafting#105]
im on the latest version of forge and extended crafting and the recipes i made for the table are not working. i looked at the craftweaker log and they say there being registered but they dont show up in jei

**Comment by BlakeBr0** [comment]
Can I get the logs and the scripts?

**Comment by TheNimbleNinja** [comment]
https://gist.github.com/TheNimbleNinja/6d3e2618382329331007c3004a589128 logs

https://gist.github.com/TheNimbleNinja/36e3cc4e2a65b3171b0b3ffc5d6a7b3f craftweaker logs

https://gist.github.com/TheNimbleNinja/6460a667432dd1f24e2d8d1b90cd050a scripts

also creating any new recipe wont work
