### ISSUE TITLE
[1.16.1] Don`t work Script with CraftingTable

### ISSUE THREAD

**Issue by Rumaruka** [BlakeBr0/ExtendedCrafting#108]
I don`t sure, but I have a bug with Crafting Table with Tier
Please, Can you watch it?

**Screenshots / Scripts / Logs**
![image](https://user-images.githubusercontent.com/8148679/90175631-20fb7b00-ddc1-11ea-8aad-fc3ce63be153.png)
`mods.extendedcrafting.TableCrafting.addShaped("mining_dimension_2",2,<item:mining_dimension:teleporter>, [
	[<item:minecraft:oak_log>, <item:minecraft:oak_log>, <item:minecraft:oak_planks>, <item:minecraft:oak_log>], 
	[<item:minecraft:oak_log>, <item:minecraft:oak_log>, <item:minecraft:stone_pickaxe>, <item:minecraft:oak_planks>], 
	[<item:minecraft:iron_pickaxe>, <item:minecraft:oak_log>, <item:minecraft:oak_planks>, <item:minecraft:oak_planks>], 
	[<item:minecraft:wooden_pickaxe>, <item:minecraft:oak_planks>, <item:minecraft:oak_planks>, <item:minecraft:oak_log>], 
	[<item:minecraft:stone_pickaxe> , <item:minecraft:oak_planks>, <item:minecraft:iron_pickaxe> , <item:minecraft:oak_log>], 
	[<item:minecraft:oak_log>, <item:minecraft:oak_log>, <item:minecraft:oak_planks>, <item:minecraft:oak_log>]
]);`

**Versions (please complete the following information):**
 - Minecraft: 1.16.1
 - Forge:32.0.108
 - Cucumber:4.0.1
 - Extended Crafting:3.0.0
 - CraftTweaker (if applicable):7.0.0.23

**Comment by BlakeBr0** [comment]
Did you make this with the recipe maker? If so update to 3.0.1 and remake it. Let me know if that fixes it.

**Comment by Rumaruka** [comment]
Yes, its work, but I think recipe maker have problem with ingredients because in clipboard coped don`t all
Close
