### ISSUE TITLE
Friezes at the entrance to the maximum workbench

### ISSUE THREAD

**Issue by Cubichesky** [BlakeBr0/ExtendedCrafting#112]
when you enter the maximum workbench, Minecraft starts to freeze every second, fps drops to 10. The average fps in the game is 200. There are 200 mods in the modpack
Versions : 1.12.2
 - Minecraft: Minecraft Twitch loader, TLauncher (pirate versions)
 - Forge: 1.12.2-forge-14.23.5.2854
 - Extended Crafting: ExtendedCrafting-1.12.2-1.5.6

**Comment by BlakeBr0** [comment]
I no longer support the 1.12 version.
