### ISSUE TITLE
.anyDamage() crattweaker tag does not work in Extended Crafting tables

### ISSUE THREAD

**Issue by NickTimmermans26** [BlakeBr0/ExtendedCrafting#114]
**Describe the bug**
When adding the .anyDamage() tag to a tool (I've tried the immersive engineering hammer, immersive engineering wirecutter, vanilla iron hoe and mapperbase hammer), the tool does not allow for a second craft. The first craft will work and reduce the durability of the tool by 1 but then the recipe does not work after that. Here is my script for the recipe of a copper plate using a tool and a copper ingot :

`mods.extendedcrafting.TableCrafting.addShapeless("shapeless_copper_plate_expert", 1, <item:immersiveengineering:plate_copper>, [<item:minecraft_iron_hoe>.anyDamage().transformDamage(), <tag:forge:ingots/copper>]); 
`
The recipe does work for a vanilla craftingtable if added for it.

**To Reproduce**
Add any recipe using crafttweaker that uses a tool which looses durability per craft through the .anyDamage() tag.

**Expected behavior**
That using a tool with less then full durability allows for the crafting of the recipe.

**Screenshots / Scripts / Logs**
-

**Versions (please complete the following information):**
 - Minecraft: 1.16.4
 - Forge: 35.1.7
 - Cucumber: Cucumber-1.16.4-4.1.5.jar
 - Extended Crafting: ExtendedCrafting-1.16.4-3.1.2.jar
 - CraftTweaker (if applicable): CraftTweaker-1.16.4-7.0.0.63.jar
 - JeiTweaker: JEITweaker-1.16.4-1.0.1.5.jar
 - Packmode: packmode-1.16.4-3.1.0.jar

I included those last two because they also deal with crafttweaker.

**Comment by NickTimmermans26** [comment]
Extra note: I just tested it with a 'shaped' recipe and that one does work! So it's only shapeless ones that fail

**Comment by BlakeBr0** [comment]
This was fixed via https://github.com/BlakeBr0/ExtendedCrafting/commit/4a45770479c01249620623dd2e4fd90f0b100a07
