### ISSUE TITLE
Custom compression recipes not taking oredict entries as ingredient and/or output

### ISSUE THREAD

**Issue by RBTC** [BlakeBr0/ExtendedCrafting#115]
**Describe the bug**

In a custom compression recipe, oredict entries are not accepted as ingredient or output.

**To Reproduce**

Try to set an oredict entry as ingredient and/or as output in a custom compression recipe

for example:
mods.extendedcrafting.CompressionCrafting.addRecipe(<ore:singularityDraconium>, <ore:ingotDraconium>, 10000, <extendedcrafting:material:11>, 1250000);

**Expected behavior**

No errors when executing the script and the recipe working with all entries of the used oredict entry.

**Screenshots / Scripts / Logs**

https://pastebin.com/FprduTCZ

**Versions:**
 - Minecraft: 1.12.2
 - Forge: 14.23.5.2854
 - Cucumber: 1.12.2-1.1.3
 - Extended Crafting: 1.12.2-1.5.6
 - CraftTweaker (if applicable): 4.1.20.607

**Comment by BlakeBr0** [comment]
You can't use an ore dictionary entry as a recipe output as it has to be a specific item.
