### ISSUE TITLE
Crafting Core Alternate Pedestals Compatibility

### ISSUE THREAD

**Issue by ghost** [BlakeBr0/ExtendedCrafting#117]
**Describe the thing**
I'm developing a fairly large modpack, and I notice that similar pedestal blocks with the same functionality are added by BetterEnd (Forge), Mystical Agriculture, Reliquary, etc. It would be awesome if we could customise valid pedestal blocks for the Crafting Core.

**Describe the solution you'd like**
A config option under `["Combination Crafting"]` in `extendedcrafting-common.toml`, or an `#extendedcrafting:pedestal` block tag that allows for the definition of new valid pedestal blocks.

**Describe alternatives you've considered**
I mean, the obvious alternative is to just deal with the current state and only use the pedestal provided by EC. In my opinion that goes against the whole concept of a feature request though.

**Comment by BlakeBr0** [comment]
This would not be as simple as a config option because there's pretty much a 0% chance that other pedestals are implemented in the exact same way. I would essentially have to implement custom handlers for every kind of pedestal which is simply just not worth the overhead.

**Comment by ghost** [comment]
Understood! Thanks for getting back to me.

**Comment by ghost** [comment]
I am very curious - would you be able to expose some sort of endpoint for the other mods to interface with as a compat? Instead of you having to define custom handlers for everything, those mods can just handle it themselves. I'd be happy to go around and post issues to each mod's tracker if this was implemented!
