### ISSUE TITLE
Autocrafting tables get destroyed when mined

### ISSUE THREAD

**Issue by mtbrenner** [BlakeBr0/ExtendedCrafting#120]
**Describe the bug**
Create a basic autocrafting table and try to mine it with a diamond pickaxe. The table is mined but is destroyed.

**To Reproduce**
See above, but all autocrafting tables are affected. The non-autocrafting tables are not affected.

**Expected behavior**
Expected result: Table in inventory

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: 1.16.4
 - Forge: 35.1.37
 - Cucumber: 4.1.6
 - Extended Crafting: 3.1.3
 - CraftTweaker (if applicable): 7,1,0,121

**Comment by Jkosio23** [comment]
duplicate #118 
Resolved in 3.1.4
