### ISSUE TITLE
Duplication bug with quark

### ISSUE THREAD

**Issue by benbenlaw** [BlakeBr0/ExtendedCrafting#124]
**Describe the bug**
Duplication bug with quark

**To Reproduce**
place a valid recipe in any of the crafting stations
click the extract button in your inventory
recipe output comes out 
recipe items inputs remain

**Expected behavior**
no duplication

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.0.46
 - Cucumber: 4.1.9
 - Extended Crafting: 3.1.4
 - CraftTweaker (if applicable): n/a

**Comment by BlakeBr0** [comment]
The screens seem to be blacklisted by default from having the buttons in the current version of Quark. I was still able to use the keybinding to reproduce this issue though. After looking into it a bit I do think it's a Quark issue, and may be related to https://github.com/Vazkii/Quark/issues/2507.

**Comment by BlakeBr0** [comment]
I believe this has been fixed.
