### ISSUE TITLE
Combination Process No Longer Working

### ISSUE THREAD

**Issue by Boolyman** [BlakeBr0/ExtendedCrafting#13]
Hey BlakeBr0 I had a large number of Combination Crafting recipes written for my pack that were working fine about a month ago (I think you were there during the preview stream).  I recently revisited that portion of the pack to write some more recipes, and none of them seem to be working.  I'm sure it's something silly I am missing, but I can't put my finger on it.  I didn't see anything in the change log that would make the recipes not work, and my recipe syntax still matches what's on the wiki.

As you can see in the picture below... the recipe shows up fine in JEI, the items on the pedastals match the orientation of the recipe in the picture, and there is almost 3million RF in the core, which is more than plenty for the recipe.  But nothing is happening.  And the GUI of the core says no recipe found.  I tried this with multiple recipes, same result.  I also tried using a lever, redstone signal, etc... but nothing.  I went back and watched the stream where these recipes were used, and it worked fine back then.
![2018-01-20 15_48_43-greenshot](https://user-images.githubusercontent.com/24765883/35189278-ef08ed00-fdfb-11e7-94b1-b1c6f8c0f7f4.png)

**Comment by Boolyman** [comment]
Also tried rolling the mod version back to the last 3 updates, and updating to the latest forge.

**Comment by BlakeBr0** [comment]
Does it work in a different instance? I just tested and it still works just fine for me. Haven't changed anything about it recently either.

**Comment by BlakeBr0** [comment]
Could also be an issue with a specific recipe(s). Does the first recipe registered work?

**Comment by Boolyman** [comment]
Ok, took me a few hours of beating my head against the wall, but apparently it is something to do with ore dic entries.  For example, the recipe in the picture above reflects ore:ingotCopper, and shows in JEI as accepting any of the copper ingots.  But in reality, your mod won't craft it with any other ingot than Mekanism copper.  Same with the other recipes that involved ore dic entries.  ore:dyeCyan would only accept the Pickle Tweaks dye, but not regular minecraft dye.  I guess your mod is only taking the first entry in the ore dic as acceptable?  I would need to make a completely different recipe for each ore dic entry if I wanted them to work.  :-/

**Comment by Boolyman** [comment]
Below are the 4 different types of copper ingots in the pack... TE, Mekanism, Immersive Engineering, and Futurepack.  They are all oredicted as ore:ingotCopper  but as you can see, only the Mekanism one starts the Extended Crafting process. 
![2018-01-21 15_29_46-greenshot](https://user-images.githubusercontent.com/24765883/35200308-69065416-fec0-11e7-8d19-bdbf51dce7f4.png)

**Comment by Boolyman** [comment]
The syntax I am using for the recipe is this...

mods.extendedcrafting.CombinationCrafting.addRecipe(<thermalfoundation:material:515>, 70000, 100, <thermalfoundation:material:512>, [<industrialforegoing:plastic>, <minecraft:redstone>, <immersiveengineering:material:20>, <ore:ingotCopper>]);

**Comment by BlakeBr0** [comment]
Yup. Turns out it only accepted the last entry because it always iterated over the entire list even if it already found a valid item. Sorry for the trouble it caused.

I'm not entirely sure when I'll get an update out with the fix, because I'm actually in the middle of adding an extrautils QED like crafter. Shouldn't be too long though.

**Comment by Boolyman** [comment]
Ok... I'll move on to other things in the pack.  If you still haven't gotten an update out in a few weeks when I need to start prepping for beta, ill just have to go through and make a recipe for ever oredic item.
