### ISSUE TITLE
Crash when opening; java.lang.NullPointerException: Rendering Block Entity

### ISSUE THREAD

**Issue by aaronhowser1** [BlakeBr0/ExtendedCrafting#130]
**Describe the bug**
I can't open the Crafting Core without crashing. Which is unfortunate, since I literally just finished making all the creative item recipes 😰

**Screenshots / Scripts / Logs**
https://pastebin.com/rAtwUH2L

**Versions (please complete the following information):**
    Minecraft: 1.16.5
    Forge: 36.1.10
    Cucumber: Cucumber-1.16.4-4.1.10
    Extended Crafting: ExtendedCrafting-1.16.4-3.1.5

**Comment by aaronhowser1** [comment]
I also tried removing the Pedestal with `ars_nouveau:ritual`, in case that was the cause, but it still crashed when opening. It didn't make a crash report that time, though.

**Comment by BlakeBr0** [comment]
Looks like a geckolib issue according to that crash log.

**Comment by BlakeBr0** [comment]
Due to inactivity I'm going to assume this was resolved. If not, you can reply here.
