### ISSUE TITLE
[1.16.5] Multiple UIs don't fit on screen when GUI size is set to "auto"

### ISSUE THREAD

**Issue by vizthex123** [BlakeBr0/ExtendedCrafting#131]
**Describe the bug**
Title

**To Reproduce**
Set the GUI size to auto and look up a recipe from the elite or ultimate table.

**Expected behavior**

**Screenshots / Scripts / Logs**
Epic table (fits, but just barely):
![image](https://user-images.githubusercontent.com/31721920/128771781-11f89d75-1c1f-4e1e-ac98-b2b00da594da.png)

Ultimate table:
![image](https://user-images.githubusercontent.com/31721920/128771706-c7cb9215-da8f-4e0c-8c7b-d408f747fed7.png)

Combination Crafting:
![image](https://user-images.githubusercontent.com/31721920/128956424-34bafc8c-48ce-41d1-9fc9-e4c49fbd1362.png)

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.2.0
 - Cucumber: 4.1.10
 - Extended Crafting: 3.1.6
 - CraftTweaker (if applicable): N/A

**Comment by BlakeBr0** [comment]
There just isn't enough space on the screen with the 'auto' gui scale, so this won't be getting 'fixed' unfortunately.

**Comment by vizthex123** [comment]
damn, rip. It used to work in the past, ah well.
