### ISSUE TITLE
[1.16.5] Combination Crafting's CraftTweaker integration isn't working like the wiki says

### ISSUE THREAD

**Issue by vizthex123** [BlakeBr0/ExtendedCrafting#132]
**Describe the bug**
The script expects 4 values when I gave 5, but the wiki says 5 are supported.

**To Reproduce**
1. Add my recipe script
2. Load the game

**Expected behavior**
When I add the recipe below, it gives me this error:
![image](https://user-images.githubusercontent.com/31721920/128954186-5fb0114e-5bad-47d1-8299-012319524f45.png)

But I followed the format the [wiki](https://blakesmods.com/docs/extendedcrafting/combination-recipes#crafttweaker) gave me.

**Screenshots / Scripts / Logs**
```mods.extendedcrafting.CombinationCrafting.addRecipe("10-amc-bag_compress_1", <item:contenttweaker:10-bag>, 10000, 100, [<item:contenttweaker:bag>, <tag:items:amc-value:1>, <tag:items:amc-value:1>, <tag:items:amc-value:1>, <tag:items:amc-value:1>, <tag:items:amc-value:1>, <tag:items:amc-value:1>, <tag:items:amc-value:1>, <tag:items:amc-value:1>, <tag:items:amc-value:1>, <tag:items:amc-value:1>]);```

CT Log:
[crafttweaker.log](https://github.com/BlakeBr0/ExtendedCrafting/files/6965216/crafttweaker.log)

**Versions (please complete the following information):**
- Minecraft: 1.16.5
- Forge: 36.2.0
- Cucumber: 4.1.10
- Extended Crafting: 3.1.6
- CraftTweaker (if applicable): 7.1.0.374

**Comment by BlakeBr0** [comment]
The powerRate parameter is meant to be the last one. I'll update the docs.

**Comment by vizthex123** [comment]
Ah, ok. Thanks.
