### ISSUE TITLE
Allows combination crafting without energy input

### ISSUE THREAD

**Issue by yuesha-yc** [BlakeBr0/ExtendedCrafting#133]
**IMPORTANT: Feature requests will only be added to the latest supported Minecraft version.**

**Describe the solution you'd like**
Allows combination crafting without energy input. (Setting the powerCost to zero still requires power input rate)

**Describe alternatives you've considered**
Implement new crafting system that does the same as combination crafting but does not need energy.

**Comment by BlakeBr0** [comment]
This sounds like https://github.com/BlakeBr0/ExtendedCrafting/issues/41.
