### ISSUE TITLE
I have a problem with the Crafting Core. When I try to open it my world crash.

### ISSUE THREAD

**Issue by Setzer1717-work** [BlakeBr0/ExtendedCrafting#134]
This is the crash log:

[crash-2021-09-15_17.42.49-client.txt](https://github.com/BlakeBr0/ExtendedCrafting/files/7173846/crash-2021-09-15_17.42.49-client.txt)

**Comment by BlakeBr0** [comment]
Does this issue still occur on the latest release? Looks like you're a couple versions behind.

**Comment by Setzer1717-work** [comment]
Oh yes, with the lastest release the problem is solved. :)
