### ISSUE TITLE
GUI crash: rendering screen

### ISSUE THREAD

**Issue by Canbinlol** [BlakeBr0/ExtendedCrafting#135]
**Describe the bug**

When trying to open the GUI of (Crafting Core).

**To Reproduce**

Put down a  (Crafting Core) and right click on it.

**Expected behavior**

Obvious lagging with cursor popping out, then minecraft no response received and crash.(client crash)

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

[crash-2021-09-25_10.42.09-client.txt](https://github.com/BlakeBr0/ExtendedCrafting/files/7229107/crash-2021-09-25_10.42.09-client.txt)

**Versions (please complete the following information):**
 - Minecraft:  1.16.5
 - Forge:  36.1.0
 - Cucumber:  Cucumber-1.16.4-4.1.10
 - Extended Crafting:  ExtendedCrafting-1.16.4-3.1.4
 - CraftTweaker (if applicable):  kubejs-1605.3.6-build.179-forge;  kubejs-create-1604.1.0.4;  kubejs-immersive-engineering-1604.1.0.12;  kubejs-mekanism-1604.1.1.6;  kubejs-thermal-1605.1.1.6

**Comment by BlakeBr0** [comment]
Does it still happen with the latest version?

**Comment by Canbinlol** [comment]
> Does it still happen with the latest version?

sorry for responding late
no, the game seams right in the latest mod version. thank you for replying.
