### ISSUE TITLE
Basic Auto Crafting Table lag

### ISSUE THREAD

**Issue by Xenaoo** [BlakeBr0/ExtendedCrafting#136]
(Sorry for my bad english)

Hello.

I play on modpack with Extended Crafting and my server have lags...

I use Observable mod for scan all tile entities.

The Basic Auto Crafting Table lag very much...

**To Reproduce**

Use Basic Auto Crafting Table. 

**Screenshots / Scripts / Logs**

![image](https://user-images.githubusercontent.com/25150236/135624302-8ffe5743-8b33-438b-abcd-5f1fee6f21aa.png)

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.2.0
 - Cucumber: 4.1.10
 - Extended Crafting: 3.1.7

 - CraftTweaker (if applicable): CraftingTweaks 12.2.1
 
 Have a good day :)
 Thanks !

**Comment by BlakeBr0** [comment]
If you disable `useVanillaRecipes` in the config does that improve it?

**Comment by Xenaoo** [comment]
#Should the Basic Crafting Table inherit vanilla crafting recipes?
useVanillaRecipes = true

If i set this line to "false", it's ok !
