### ISSUE TITLE
Recipe Maker using tags

### ISSUE THREAD

**Issue by Boolyman** [BlakeBr0/ExtendedCrafting#137]
It would be extremely helpful for us pack devs to have an option, either in the configs, or on the wand itself, to have a mode which uses the tags instead of the specific item IDs.  

I.E. `<tag:item:forge:plates/copper>` instead of `<thermal:copper_gear>`

I would say it's pretty rare for devs to not want to use tags, allowing for same-type resources between mods to be used in the recipes.  Which means, as it stands now, we have to go in and manually overwrite the Recipe Maker's syntax anyways.  Nearly every big mod out there has a lot of resource redundancy, and this would be very helpful.

**Comment by BlakeBr0** [comment]
There should be a config option in the recipe maker section to default to using tags

**Comment by Boolyman** [comment]
You are right... Sorry for the ticket.  Thanks.

**Comment by Boolyman** [comment]
Actually, it's doing the tag syntax in a way that's creating errors.

It's generating `<tag:forge:gears/iron>`

Instead of `<tag:items:forge:gears/iron>`

Is there a setting I am missing?
