### ISSUE TITLE
The workbench interface is broken

### ISSUE THREAD

**Issue by Pqvel1l** [BlakeBr0/ExtendedCrafting#141]
**Describe the bug**
The mistake is that the player interfaces fill half the screen, but only 1 is working. 
I would like you to fix it.

**To Reproduce**
Just open workbench from extended crafting.

**Expected behavior**
I wanted to see a normal workbench interface.

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).
![unkn1own](https://user-images.githubusercontent.com/90570840/139245774-e0c4c419-6ade-429e-af9e-f62fa254d748.png)
![unknow2n](https://user-images.githubusercontent.com/90570840/139245799-4e65f2a5-77cc-4a27-b471-6ae224458f66.png)

**Versions (please complete the following information):**
 - Minecraft:1.16.5
 - Forge:3.6.28
 - Cucumber:4.1.11
 - Extended Crafting:3.1.7
 - CraftTweaker (if applicable):Not used

@BlakeBr0 help please

**Comment by BlakeBr0** [comment]
Fixed with Cucumber 4.1.12
