### ISSUE TITLE
Texture issue with the Quantum Compressor

### ISSUE THREAD

**Issue by MLDEG** [BlakeBr0/ExtendedCrafting#143]
**Bug**
I'm working on a texture pack to make a dark GUI and I notice a texture bug with the Quantum Compressor when I want to click on eject.

**Screenshots**
![This is an image](https://media.discordapp.net/attachments/722587972545019984/906160781144522812/2021-11-05_13.31.24.png)

**Versions:**
 - Minecraft: 1.16.5
 - Forge: 36.2.0
 - Cucumber: 4.1.12
 - Extended Crafting: 3.1.8

Note that I created an instance with only Extended Crafting and Cucumber Library.
Thanks for your work :)

**Comment by BlakeBr0** [comment]
This is fixed in 3.1.9
