### ISSUE TITLE
Crashing (Possible due to quark Glass Item Frame- not sure)

### ISSUE THREAD

**Issue by CodWafer** [BlakeBr0/ExtendedCrafting#144]
**Describe the bug**
Game crashes when joining my world- 
A POSSIBILITY: In order to fix it I launch without, then close and launch with- it does work, the only change is that an Ender star, located in a (quark) glass item frame is no longer there.

**To Reproduce**
Steps to reproduce the behavior: I am not 100% sure, but I think it may be this:
Install extended crafting + libraries + quark
Place a glass item frame
place an ender star in it
close and relaunch
rejoin the world
(AGAIN- I AM NOT 100% SURE ABOUT THIS)

**Expected behavior**
No crash

**Screenshots / Scripts / Logs**
https://paste.ee/p/aJlN2

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.2.8
 - Cucumber: 4.1.12
 - Extended Crafting: 3.1.9
 - CraftTweaker (if applicable): (Haven't used it on Extended Crafting) 7.1.2.456

**Comment by BlakeBr0** [comment]
That crash log is pointing to the compressor not being able to check a recipe because of an unrecognized tag. Is there anything potentially messing with tags in your modpack?

**Comment by CodWafer** [comment]
[modlist.txt](https://github.com/BlakeBr0/ExtendedCrafting/files/7575523/modlist12345.txt)
Not sure.
I have been making a datapack that USES tags to identify some items... Not too sure though

**Comment by BlakeBr0** [comment]
Is this an ongoing issue?

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
