### ISSUE TITLE
Empty tag != item without tag

### ISSUE THREAD

**Issue by Sunekaer** [BlakeBr0/ExtendedCrafting#145]
**Describe the bug**
Items with empty tag isn't seen as the same as items without tag.

So if compression is started with **thermal:rf_potato{}** when **thermal:rf_potato** wont work 

**Expected behavior**
both to work

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.2.20
 - Cucumber: Cucumber-1.16.5-4.1.12.jar
 - Extended Crafting: ExtendedCrafting-1.16.5-3.1.10.jar
 - CraftTweaker (if applicable):

**Comment by BlakeBr0** [comment]
I don't believe that those items would stack in an inventory anyways right? I can look into adding a special case for this if it doesn't add too much complexity, though I'm not entirely sure if it would result in unexpected behavior.

I would have to check if the item has an empty tag and remove it. Currently the compressor doesn't modify the items put into it, so this would be the only case where that happens. I'm not entirely sure if I want to do that.

**Comment by godefroi** [comment]
@BlakeBr0 Capacitatoes don't stack, so your question is unanswerable.

**Comment by BlakeBr0** [comment]
As an update to this:

I plan to make it so the compressor can take and store multiple variants of the same item (ex. tags, different nbt), which would solve this issue.
