### ISSUE TITLE
[1.16.5] Textures don't seem to be animated anymore?

### ISSUE THREAD

**Issue by Elfinlocks** [BlakeBr0/ExtendedCrafting#149]
**Describe the bug**
Textures for singularities, ultimate ingot, etc, are not animated - is this a deliberate change, or could something on my end be somehow interfering?

**Screenshots / Scripts / Logs**
N/A

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.2.22
 - Cucumber: 4.1.12
 - Extended Crafting: 3.1.10
 - CraftTweaker (if applicable): 7.1.2.491

**Comment by BlakeBr0** [comment]
They should be animated. Maybe you have something installed that disables animated textures.
