### ISSUE TITLE
[Feature Request] Extended Crafting GUI

### ISSUE THREAD

**Issue by Cazadorsniper** [BlakeBr0/ExtendedCrafting#15]
Can we get an ingame crafting GUI that allows pack makers to make adding/removing recipes easier that is compatible with the /CTGUI command in CraftTweaker for the crafting tables?

**Comment by BlakeBr0** [comment]
I added an item that you can use to create crafttweaker scripts for the grid contents of a table via right click. It should mostly accomplish the same thing, hopefully.
