### ISSUE TITLE
Getting an odd crash referencing a pedestal that isn't even used in the pack

### ISSUE THREAD

**Issue by Boolyman** [BlakeBr0/ExtendedCrafting#152]
**Describe the bug**
````
[12:31:32] [Worker-Main-9/ERROR]: Exception caught during firing event: Registry Object not present: extendedcrafting:pedestal
````

**To Reproduce**

Install Extended Crafting and then load the pack.

**Expected behavior**
I expect the pack not to crash.

**Screenshots / Scripts / Logs**
Crash Report:
https://pastebin.com/ja5yW52G

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.2.29
 - Cucumber: 1.16.5-4.1.12
 - Extended Crafting: 1.16.5-3.1.11
 - CraftTweaker (if applicable): 1.16.5-7.1.2.505

**Comment by BlakeBr0** [comment]
Is this still an issue you're facing?

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
