### ISSUE TITLE
Freely available ultimate singularities

### ISSUE THREAD

**Issue by kevinkjt2000** [BlakeBr0/ExtendedCrafting#154]
**Describe the bug**
Ultimate singularities are available for free from the ultimate auto crafting table. Seems similar to #116 

**To Reproduce**
* Place an ultimate autocrafting table
* Open its GUI

**Expected behavior**
I expected to have to provide one of each singularity.

**Screenshots / Scripts / Logs**
https://paste.ee/p/i17Nu
![image](https://user-images.githubusercontent.com/4098674/164986257-94b9d138-c5e4-41c5-8e7f-24b62dca95cd.png)

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 1.16.5-36.2.34
 - Cucumber: 1.16.5-4.1.12
 - Extended Crafting: 1.16.5-3.1.11
 - CraftTweaker (if applicable): N/A

**Comment by kevinkjt2000** [comment]
Additionally, if the table receives power, it starts making them automatically without needing to manually take them from the GUI.

**Comment by Valdan20** [comment]
i have the same problem, but only on servers

**Comment by BulletSheep** [comment]
I got the Same Problem but not everytime. sometimes after a server restart it works sometimes not

**Comment by BulletSheep** [comment]
> i have the same problem, but only on servers

I got a Solution if its possible for Your Server and Modpack then use: ExtendedCrafting-1.16.5-3.1.10 
I Tested on my Server its the Solution for the Time

**Comment by BlakeBr0** [comment]
I just released version 3.1.12 which should fix this issue

**Comment by MechOrigin** [comment]
Thanks @BlakeBr0 <3
