### ISSUE TITLE
Data Packs for 1.18.2

### ISSUE THREAD

**Issue by SGZ-Creations** [BlakeBr0/ExtendedCrafting#158]
Any info to specify what table to add recipes too.

**Comment by BlakeBr0** [comment]
Not entirely sure what you mean. You can read the docs on my website for adding recipes using datapacks: https://blakesmods.com/docs/extendedcrafting

**Comment by SGZ-Creations** [comment]
https://blakesmods.com/docs/extendedcrafting/table-recipes

This was what i needed for creating recipes using datapacks thanks.

**Comment by SGZ-Creations** [comment]
https://blakesmods.com/docs/extendedcrafting/table-recipes

This was what i needed for creating recipes using datapacks thanks.

**Comment by SGZ-Creations** [comment]
https://blakesmods.com/docs/extendedcrafting/table-recipes

This was what i needed for creating recipes using datapacks thanks.
