### ISSUE TITLE
Ultimate Singularities are Free

### ISSUE THREAD

**Issue by tmanfoo1** [BlakeBr0/ExtendedCrafting#159]
**Describe the bug**
So, If I take an extended automated crafting table of max teir, and insert any item, then take that item out it will give me the option to craft ultimate singularities for free. NOTE This ONLY seems to happen on servers!

**To Reproduce**
1: Install the modpack andromeda automation
2: boot up a server with said modpack
3: place that extended crafting table and repeat the steps above

https://www.curseforge.com/minecraft/modpacks/andromeda-automation

NOW I understand that you likely would thing this is a configuration or craft tweaker error, I have been through the logs as well as the config at least 5 times to double and tripple check that is not the case!

**Expected behavior**
With nothing in the crafting table it should craft nothing

**Screenshots / Scripts / Logs**

https://user-images.githubusercontent.com/93341184/184260644-15633eaf-6835-43ff-875c-1871ebba1a46.mp4

**Versions (please complete the following information):**
 - Minecraft: 1.18.2
 - Forge: 40.1.68
 - Cucumber: 
Cucumber-1.18.2-5.1.2.jar
 - Extended Crafting: ExtendedCrafting-1.18.2-4.1.1.jar
 - CraftTweaker (if applicable): CraftTweaker-forge-1.18.2-9.1.164.jar

**Comment by BlakeBr0** [comment]
Is this a consistent issue between server restarts?

**Comment by tmanfoo1** [comment]
Yes.

**Comment by BlakeBr0** [comment]
I'm going to close this as it's for 1.18 which no longer gets updates. I believe this is fixed in newer versions.
