### ISSUE TITLE
Custom compressor recipes dont show in JEI

### ISSUE THREAD

**Issue by benbenlaw** [BlakeBr0/ExtendedCrafting#164]
**Describe the bug**
Custom compressor recipes dont show in JEI

**To Reproduce**
create a custom recipe:
{"type": "extendedcrafting:compressor", "powerCost": 100000, "inputCount": 1, "ingredient": { "item": "minecraft:dirt" }, "catalyst": { "item": "minecraft:gold_ingot" }, "result": { "item": "minecraft:dirt" } }

**Expected behavior**
recipe to show in JEI

**Screenshots / Scripts / Logs**
![image](https://user-images.githubusercontent.com/42780877/200615063-665e4693-3796-4b64-95d1-9abf30b14cd5.png)
clicking in the circle will show the recipe
![image](https://user-images.githubusercontent.com/42780877/200615184-ad453abb-7769-44d7-b606-befe1c5fe5f9.png)
clicking on dirt in JEI will not show the recipe
**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Forge: 43.1.43
 - Cucumber: 1.19.2-6.0.3.
 - Extended Crafting: 1.19.2-5.1.2
 - CraftTweaker (if applicable): none

**Comment by BlakeBr0** [comment]
I was not able to reproduce this. That recipe worked fine when I tested. Maybe there's an issue with your datapack?

**Comment by benbenlaw** [comment]
so an update on it press the uses button does show the recipe but the recipe button does not

**Comment by benbenlaw** [comment]
will take another look with fresh eyes and let you know

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
