### ISSUE TITLE
Ender Crafter isn't seen as inventory/container as it is in later versions

### ISSUE THREAD

**Issue by calvissuperman** [BlakeBr0/ExtendedCrafting#165]
**Describe the bug**
Using other mod items such as Botania's red string container, or RFTools' processor, the ender crafter is not seen as a suitable container or inventory. Yet the Automation Interface interacts with the ender crafter just fine and is seen properly.

**To Reproduce**
Steps to reproduce the behavior: Use any method of inserting items into the ender crafter other than the Automation Interface, and items will not flow. I am using a redstringed container from Botania, which should automatically see this block and become a connection. Then you can pipe items into the redstringed container and the items will go straight into the ender crafter.

**Expected behavior**
The ender crafter should be seen as a container and be able to insert and remove items just like a furnace, which seems to be working fine in later versions of minecraft (1.16.5)

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable). [Youtube Video](https://youtu.be/VyeO-bjAFmA?t=690) at 11:30 he proves this is working properly, yet in my world the red stringed container does not see the Ender Crafter as a suitable pair. [Screenshot](https://imgur.com/a/MjXfJva)

**Versions (please complete the following information):**
 - Minecraft: 1.12.2
 - Forge: 14.23.5.2860
 - Cucumber: 1.1.3
 - Extended Crafting: 1.7.0
 - CraftTweaker (if applicable): 1.12-4.1.20.680

**Comment by BlakeBr0** [comment]
It's definitely possible that the ender crafter works differently post 1.12 as I've rewritten the mod since then. The 1.12 version is end of life at this point so I won't be making any changes to it.
