### ISSUE TITLE
Weird bug where game wont start keeps crashing on server startup

### ISSUE THREAD

**Issue by thebikwirm** [BlakeBr0/ExtendedCrafting#166]
added mod to server and server doesnt start has worked before

- Minecraft: 16.5
 - Forge: 36.2.39
 - Cucumber: 4.1.12 
 - Extended Crafting: 3.1.12
 - CraftTweaker (if applicable): 7.1.2.515
[crash-2022-12-06_06.49.09-fml.txt](https://github.com/BlakeBr0/ExtendedCrafting/files/10163611/crash-2022-12-06_06.49.09-fml.txt)

**Comment by BlakeBr0** [comment]
That error is related to mixin, which this mod doesn't use. Tinkers' is also mentioned in that crash log. I'm not entirely sure what the problem could be.

**Comment by thebikwirm** [comment]
is it possible to fix it?

**Comment by BlakeBr0** [comment]
Did you find a solution? Sorry for the late reply. I'm not really sure where the error would be coming from

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
