### ISSUE TITLE
Ultimate Auto crafter does not stop crafting when missing ingredients 

### ISSUE THREAD

**Issue by braingkk** [BlakeBr0/ExtendedCrafting#168]
Note this is on a heavily modded pack called "Ragnamod VI". I have not tested this on a bare install of cucumber and extended crafting, but if needed, I can try to reproduce on a clean install.

**Describe the bug**
If the inventory above the ultimate auto crafter has any unrelated items in it, the auto crafter will continue to run as long as there are ANY items in its inventory and there are no further interactions

**To Reproduce**
1) Place and power an ultimate auto crafting table with an inventory above it containing a useless item. 

2) In the top left corner of the crafter place a stack of the item that will be needed for the craft.

3) Let the crafter pull the rest of the requisite ingredients from the above inventory.

4) Enjoy the duped materials.

**Expected behavior**
I would have expected the crafter to stop once any of the required ingredients were exhausted.

**Screenshots / Scripts / Logs**
Here is a gif of me replicating the glitch
https://puu.sh/Jx8i6/27e1777c60.mp4

**Versions (please complete the following information):**
 - Minecraft: 1.1.6.5
 - Forge: 36.2.34
 - Cucumber: 4.1.12
 - Extended Crafting: 3.1.12
 - CraftTweaker (if applicable):

**Comment by SikiciBebek** [comment]
Iam playing on 1.20.1 with the newest version and still having this issue. Also i cant take out the Singularity even tho the recipe is working and the result is popping off
