### ISSUE TITLE
QCompresser Recipes missing from REI

### ISSUE THREAD

**Issue by FooterManDev** [BlakeBr0/ExtendedCrafting#169]
**Describe the bug**
With Roughly Enough Items installed, no recipes for QC show **unless** you right click/press U on the block itself. For example:
When looking for Lapis Singularity recipes, nothing happens. If you check the uses for the QCompressor it shows the recipe there. 

**To Reproduce**
Install REI with EC
Check QC recipes.
**Expected behavior**
QC recipes to show when checking for recipes like Singularities.
**Screenshots / Scripts / Logs**
[latest.log](https://gist.github.com/FooterMan14/e00af952d813794f0e1dc7e859bd9199)

**Versions (please complete the following information):**
 - Minecraft: 1.19.2 
 - Forge: 43.2.4
 - Cucumber: 6.0.6
 - Extended Crafting: 5.1.4
 - CraftTweaker (if applicable):

**Comment by TheLord9000** [comment]
Also for jei this bug exists
