### ISSUE TITLE
Disabled items still obtainable.

### ISSUE THREAD

**Issue by MindBrain27** [BlakeBr0/ExtendedCrafting#172]
**Describe the bug**
After disabling the Handheld Crafting Table it is still craftable. It does not appear in the JEI list but seeing uses for a Crafting Table will still show the recipe for the Handheld Crafting Table, and it is craftable. I would imagine this is not the only item this is happening for. I have about 80% of the mod disabled. This has been disabled for months, not a recent change.

**To Reproduce**
Disable the Handheld Crafting Table in the config, restart the game, craft the Portable Crafting Table.

**Expected behavior**
Disabled items to not be craftable.

**Screenshots / Scripts / Logs**
![extended error 1](https://user-images.githubusercontent.com/74363414/223865880-3faff42e-7073-4cc4-8289-8164a8cf003e.PNG)
![extended error 2](https://user-images.githubusercontent.com/74363414/223865902-a053faec-93e6-42af-9fa4-54602a0219ec.PNG)
![extended error 3](https://user-images.githubusercontent.com/74363414/223865928-d9c033c3-a47d-4560-acbd-76373bbc5bd8.PNG)
![extended error 4](https://user-images.githubusercontent.com/74363414/223865946-86b6117c-46cb-426d-a5c0-d90b48e1a87a.PNG)

All scripts containing anything to do with Extended Crafting found below.
https://hastebin.com/share/geradeyoyo.php
https://hastebin.com/share/iqizihuzuj.csharp

I cannot find a hastebin/pastebin site good enough to support a full log? Can add if needed and shown an actually good version of hastebin or something along those lines.

**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Forge: 43.2.6
 - Cucumber: Cucumber-1.19.2-6.0.6.jar
 - Extended Crafting: ExtendedCrafting-1.19.2-5.1.4.jar
 - CraftTweaker (if applicable): CraftTweaker-forge-1.19.2-10.1.36.jar (not actually using)
 - KubeJS: kubejs-forge-1902.6.0-build.142.jar (actually using for scripts)

**Comment by BlakeBr0** [comment]
From what I can tell it's just the handheld crafting table
