### ISSUE TITLE
Mod Compatibility Refined & AE 2

### ISSUE THREAD

**Issue by SGZ-Creations** [BlakeBr0/ExtendedCrafting#173]
**IMPORTANT: Feature requests will only be added to the latest supported Minecraft version.**

**Describe the solution you'd like**
AE2 And Refined storage Compatibility by patterns to use the bigger crafting tables.

**Describe alternatives you've considered**
A addon mod. that don't seem to exist.

**Additional context**
out of perspective an addon would be the best rather than adding it to the mod directly
also best maintained by the main author or in relation to communicate with each other.

**Comment by BlakeBr0** [comment]
I would consider this out of scope

**Comment by SGZ-Creations** [comment]
Why may i ask? 

All i where hoping for is a new type of pattern that has the 9x9 size in the/a machine.
![image](https://user-images.githubusercontent.com/59801736/227761448-1674f8c7-3a36-4ad1-bca9-5879a8e8598c.png)
Everything else is as normal.
