### ISSUE TITLE
Cannot craft ultimate singularity

### ISSUE THREAD

**Issue by eliphatfs** [BlakeBr0/ExtendedCrafting#174]
**Describe the bug**
Cannot craft ultimate singularity.

I am playing latest FTB University 1.16, hosted on a dedicated server.

**To Reproduce**
1. Place an ultimate crafting table.
2. Open recipe in JEI and send recipe to the table.
3. Click the ultimate singularity to attempt to move out.

**Expected behavior**
The ultimate singularity is moved out.

Actually it does not. It seem to be moved out for a short time, but jumps back.
Holding shift does move it out, but it jumps back when I want to do anything with the ultimate singularity.

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).
![image](https://user-images.githubusercontent.com/23738781/229992018-b6009b0a-8126-4929-aeab-e63a3250f409.png)
[latest.log](https://github.com/BlakeBr0/ExtendedCrafting/files/11155603/latest.log)

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.2.35
 - Cucumber: 
 - Extended Crafting: 3.1.12
 - CraftTweaker (if applicable):

**Comment by eliphatfs** [comment]
It also happens with an auto crafting table. Saving recipe shows '0x Air'.
![image](https://user-images.githubusercontent.com/23738781/229994243-9c58cb97-f9df-4ba6-93ab-ed69cc76c1fa.png)

**Comment by eliphatfs** [comment]
Manually placing the singularities does not help either.

**Comment by BlakeBr0** [comment]
I'm going to close this as the 1.16 version is no longer being updated. If you are still having this issue on a newer release you can reply here.

**Comment by 1luik** [comment]
[
1.19在Age of Fate  3.1.5版本也有
在单人看不见'The Ultimate Singularity'的合成表在服务器可以显示但是不可以合成
]
1.19 is also available in Age of Fate 3.1.5 version

The composite table of 'The Ultimate Singularity' is not visible to a single person and cannot be synthesized on the server

![973dad08f204f06ed2ffd38c416a2ab3](https://github.com/BlakeBr0/ExtendedCrafting/assets/102875437/16c0b1ed-9575-446e-91ba-373a87477af8)
![03fcfe1363ad233cdd2ef83701a6edcf](https://github.com/BlakeBr0/ExtendedCrafting/assets/102875437/1df5d39e-6403-491e-910b-d94e6651f3fc)
