### ISSUE TITLE
Combination Crafting Recipe List

### ISSUE THREAD

**Issue by PedroMLV** [BlakeBr0/ExtendedCrafting#176]
Hi, Ive been using the mod in 1.18.2 and I noticed that in other versions of the mod there is a recipe list on the combination crafting mod, how do I turn that on? Was it removed?

![Image](https://github.com/BlakeBr0/ExtendedCrafting/assets/126025436/26bc5bd7-0d08-4160-be1a-1ccd7ffc406b)

**Comment by BlakeBr0** [comment]
This was removed post-1.12 and re-added in 1.19. Unfortunately this feature didn't make it back into the 1.18 version.
