### ISSUE TITLE
More Singularity GAME Display

### ISSUE THREAD

**Issue by mogcid** [BlakeBr0/ExtendedCrafting#180]
**Describe the bug**
More Singularity GAME Display

**To Reproduce**
Creation of new singularity

**Expected behavior**
More Singularity GAME Display

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Forge:  43.2.19
 - Cucumber: 1.19.2-6.0.7
 - Extended Crafting: 1.19.2-5.1.7
 - CraftTweaker (if applicable): no

**Comment by BlakeBr0** [comment]
I'm not sure what you're trying to say here

**Comment by mogcid** [comment]
After adding new singularities, they are no longer displayed in JEI, only the ultimate remains and I can clearly see the craft with the singularities created previously

**Comment by BlakeBr0** [comment]
Is this still an issue you're experiencing?

Edit: I just released a new version for 1.19 which may have fixed the issue you were experiencing.

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
