### ISSUE TITLE
[1.19.2] Combination crafting, catalyst nbt data

### ISSUE THREAD

**Issue by YOYOK9** [BlakeBr0/ExtendedCrafting#181]
**Describe the bug**
Making a custom combination recipe. Trying to add an item to the Catalyst slot (on top input) that has nbt data. Kubejs script doesn't error, however I only get a partial item (base item no nbt data). Due to this, any item within that items group can be used

ex: Potion of night vision as the catalyst in the script, but in game any potion is useable. 

Or in my case, Gateways To Eternity custom portal recipes. 

**To Reproduce**
Make a combination recipe with any items that use the item.of(...) as a catalyst. EX potions 

**Expected behavior**
The catalyst to only accept the specific item required, not everything within that group

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

Crafting recipe in game: https://puu.sh/JRepc/6b7b3f0576.png
(already chatted with the dev of gateways, seems to be nbt related)

My Script: https://gist.github.com/YOYOK9/e81909fc2db9fb6959438337e4685ab0

**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Forge: 43.2.23
 - Cucumber: 1.19.2-6.0.10
 - Extended Crafting: 1.19.2-5.1.9
 - CraftTweaker (if applicable): N/A
 - Kubejs: 1902.6.2-build.15

**Comment by BlakeBr0** [comment]
I just tested with the following datapack recipe and it requires the correct NBT as expected:

```json
{
  "type": "extendedcrafting:combination",
  "powerCost": 400000,
  "input": {
    "type": "forge:nbt",
    "item": "extendedcrafting:recipe_maker",
    "nbt": {
      "Shapeless": true,
      "Type": "Datapack"
    }
  },
  "ingredients": [
    {
      "item": "minecraft:iron_ingot"
    },
    {
      "item": "minecraft:iron_ingot"
    },
    {
      "item": "minecraft:iron_ingot"
    },
    {
      "item": "minecraft:iron_ingot"
    },
    {
      "item": "minecraft:iron_ingot"
    },
    {
      "item": "minecraft:iron_ingot"
    },
    {
      "item": "minecraft:iron_ingot"
    },
    {
      "item": "minecraft:iron_ingot"
    }
  ],
  "result": {
    "item": "minecraft:stone"
  }
}
```

I'm not sure but I would guess the `Item.of` function doesn't result in the same ingredient as above.

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
