### ISSUE TITLE
Failed to load datapacks

### ISSUE THREAD

**Issue by ErickThomaz** [BlakeBr0/ExtendedCrafting#182]
**Describe the bug**
When Using more recent version of Extended my server crash on start load in datapack load.
 I downgrade the version to 6.0.1 and server loads now

**To Reproduce**
Use Mohist/Arcligth, start server using most recent version of Cucumber and Extended

**Expected behavior**

**Screenshots / Scripts / Logs**
https://gist.github.com/ErickThomaz/168c1fb8ac464b2d1d9a8d642291048e

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.2.1
 - Cucumber:7.0.4
 - Extended Crafting:6.0.4
 - CraftTweaker (if applicable):

**Comment by BlakeBr0** [comment]
If you go into the config and disable `defaultRecipes` in the singularity section does that solve it? It seems that the custom server implementation you're using modifies the vanilla recipe manager in a way that makes it incompatible.

**Comment by f1den** [comment]
q!
Same problem 🥶

**Comment by f1den** [comment]
### **Fixed** by making steps:

1. go to "Server_Folder\\config"
2. find "extendedcrafting-common.toml"
3. on 10 line find "defaultRecipes"
4. set it to "false" (if true)

$$ Profit $$
