### ISSUE TITLE
Incorrect Combination Crafting causing errors

### ISSUE THREAD

**Issue by DaRubb3rDucky1** [BlakeBr0/ExtendedCrafting#183]
**Describe the bug**
When crafting a combination recipe with the crafting core with the wrong amount of inputs, the game bugs out and stops responding

**To Reproduce**
1. Create a crafting recipe with the crafting core
2. Put in the wrong number of inputs
3. Start the craft

**Expected behavior**
I expected the craft to not start until I had all the

**Screenshots / Scripts / Logs**
[This is a link to my Mega file with everything related to his bug. My log file, vid showing what's happening, and my KubeJS script that adds the recipe.](https://mega.nz/folder/nmpHRT7J#8lC89wqs6P4SSK2iWN9T9A)

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.1.30
 - Cucumber: 1.20.1-7.06.
 - Extended Crafting: 1.20.1-6.0.4
 - CraftTweaker (if applicable): N/A
 - KubeJS: 2001.6.4-build.114
 - Singleplayer or Multiplayer: Singleplayer

**Comment by BlakeBr0** [comment]
Is this still an issue you're experiencing? The log files are spammed with like 40k lines about GL errors, maybe that's related to your issue?

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
