### ISSUE TITLE
Crash on quantum compressor ejecting

### ISSUE THREAD

**Issue by Dragonir44** [BlakeBr0/ExtendedCrafting#185]
**Describe the bug**
When I would like to use the utlimate auto crafting table to craft the ultimate singularity, I use the pipez pipe to link my quantum compressor  but it not extract the singularities into the crafting table (I saved the recipe into it before). So i try to click on the eject button to see if it's allow the sigularities to be extracted but my server crashed after set the eject on four quantum compressor.

**To Reproduce**
- Make singularities
- When a singularities is finished, click on eject button
- Use a item pipe from pipez to try extract the singularities (optionnal i think)

**Expected behavior**
The game or server crashed

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).
https://gist.github.com/Dragonir44/2f86a985ed1d50688c25c4dda567a5ea

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.2.19
 - Cucumber: 1.20.1-7.0.7
 - Extended Crafting: 1.20.1-6.0.5
 - Singleplayer or Multiplayer: both

**Comment by BlakeBr0** [comment]
This is caused by turning on eject mode while the output is being created and limit inputs is on.
