### ISSUE TITLE
Ultimate Singularity Missing in JEI but not in REI

### ISSUE THREAD

**Issue by DarkBladeNemo** [BlakeBr0/ExtendedCrafting#186]
**Describe the bug**
The Ultimate Singularity doesn't show in JEI but it does show in REI.

**To Reproduce**
Steps to reproduce the behavior: Install REI and it shows, Install JEI and it doesn't.

**Expected behavior**
To show up so I can craft it.

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.2.19
 - Cucumber: 7.0.7
 - Extended Crafting: 6.0.5
 - CraftTweaker (if applicable):
 - Singleplayer or Multiplayer: Singleplayer

**Comment by Shotguun29** [comment]
I second this, I have noticed the issues here. I cant even find it in the creative tab.
Minecraft: 1.20.1
Forge: 47.2.20
Cucumber: 7.0.7
Extended Crafting: 6.0.5
CraftTweaker (if applicable): yes
Singleplayer or Multiplayer: Singleplayer

**Comment by SikiciBebek** [comment]
Hey :D
same issue here. i tried to remake it with kubejs, but kinda failed tbh. 
The Recipes working and also the NBTs does. But its not rly what it should look like.
Any idea how i can fix this so far?
![image](https://github.com/BlakeBr0/ExtendedCrafting/assets/98269183/a76fdbb0-f0ba-465b-91e1-8aebee7e5914)
![image](https://github.com/BlakeBr0/ExtendedCrafting/assets/98269183/bc1019eb-7e02-4ba6-8185-4fda07248c28)
![image](https://github.com/BlakeBr0/ExtendedCrafting/assets/98269183/c4965675-5621-4f10-a0de-8a6b685ead30)

**Comment by SikiciBebek** [comment]
I could fix that crafting recipe issue by using ".strongNBT()". It works now. But the only 1 singularity (withour resource) is popping off in JEI/Creative inventory
and idea how to fix that?

![image](https://github.com/BlakeBr0/ExtendedCrafting/assets/98269183/d68835a5-6570-40f1-968d-37a298c2fd80)

**Comment by BlakeBr0** [comment]
@SikiciBebek The built in recipe should still exist if you are experiencing the same issue. Checking the usages of one of the Singularities should show it, assuming you haven't disabled it yourself.
