### ISSUE TITLE
Autocrafter unlimited results + Cant take out singularity

### ISSUE THREAD

**Issue by SikiciBebek** [BlakeBr0/ExtendedCrafting#187]
**Describe the bug**
Even tho the ingeridients run out the basic autocrafter keeps crafting the same item.
The result for the singularity is being shown but u cant take it out.

**To Reproduce**
Place and craft

**Expected behavior**
Not to dupe.
Crafing ultimate singularity

**Screenshots / Scripts / Logs**
No scripts but logs
[latest.log](https://github.com/BlakeBr0/ExtendedCrafting/files/14786874/latest.log)

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.2.20
 - Cucumber: 7.0.7
 - Extended Crafting: 6.0.6
 - CraftTweaker (if applicable): No / Kubejs is with a changed ultimate ingot recipe
 - Singleplayer or Multiplayer: Multiplayer. Singleplayer is working fine
 
 I removed the Configs and let them recreated again. But the issue is still there.
All other recipes are working fine btw exept of the Ultimate singularity
![image](https://github.com/BlakeBr0/ExtendedCrafting/assets/98269183/bde4780d-d02e-4a0c-9bfc-e2e4a1ad61cf)

**Comment by SikiciBebek** [comment]
![image](https://github.com/BlakeBr0/ExtendedCrafting/assets/98269183/5a8c13b2-8c49-4278-bdc6-1cb66ea90443)

**Comment by BlakeBr0** [comment]
I wasn't able to reproduce the Ultimate Singularity issue but I made some changes that may fix it. If not you can reply here.
