### ISSUE TITLE
Does not remove the recipe from the Eidolon : Rehonored mod.

### ISSUE THREAD

**Issue by C-A-X-A-R-O-K** [BlakeBr0/ExtendedCrafting#188]
Does not remove the recipe from the Eidolon : Rehonored mod.

Maybe i not incorrect typing the information. But with other mods, everything works without errors.
![2](https://github.com/BlakeBr0/ExtendedCrafting/assets/166731349/680c2181-2d3e-4a4e-b824-1ce95c5a1a3c)
![1](https://github.com/BlakeBr0/ExtendedCrafting/assets/166731349/c1077301-94b5-4d90-974e-62a640fdcb44)

 - Minecraft: 1.20.1
 - Forge: 47.2.0
 - Cucumber: 1.20.1-7.0.8.jar
 - Extended Crafting: 1.20.1-6.0.7.jar
 - CraftTweaker: 1.20.1-14.0.38.jar
 - Singleplayer.

**Comment by BlakeBr0** [comment]
You're going to have to look into how to remove recipes from whichever mod adds that block. Extended Crafting does not add that block, and isn't used to modify recipes from other mods.
