### ISSUE TITLE
Add items with JEI + button not working with the recent JEI versions

### ISSUE THREAD

**Issue by jerem2772** [BlakeBr0/ExtendedCrafting#189]
**Describe the bug**
With the JEI version 15.10.0.35 it's impossible to add items in crafting table with the JEI "+" button (move items)

**To Reproduce**
Open the ultimate crafting table, clic on a craft in JEI, try to add all items to craft the recipe, and nothing happens.

**Expected behavior**
All items add in the Ultimate crafting table in right position.

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.3.5
 - Cucumber: 7.0.9
 - Extended Crafting: 6.0.7
 - CraftTweaker (if applicable): 14.0.40
 - Singleplayer or Multiplayer: Multiplayer
 - JEI: 15.10.0.35

 - Modpack : Ozone Skyblock Reborn 1.9.4 [https://www.curseforge.com/minecraft/modpacks/ozone-skyblock-reborn](url)

A issue was opened on JEI's Github
[https://github.com/mezz/JustEnoughItems/issues/3665](url)

**Comment by mezz** [comment]
This was an issue on my side, (see https://github.com/mezz/JustEnoughItems/issues/3665) and has been fixed in JEI `15.11.0.43`
