### ISSUE TITLE
Server Overloaded

### ISSUE THREAD

**Issue by CJMinecraft01** [BlakeBr0/ExtendedCrafting#19]
So I am currently making a modpack and I've added Extended Crafting and I've discovered that about every  minute or so I get a massive lag spike due to a `Can't keep up! Did the system time change, or is the server overloaded? Running 30345ms behind, skipping 606 tick(s)` message. This happens very frequently.

To try and figure out the cause of this I tried removing different mods until I found that by disabling Extended Crafting, the lag all of a sudden has gone. Now my world is a void world and I have not placed any blocks from Extended Crafting and like I said, the lag disappears when Extended Crafting is disabled.

I think this mod is an awesome mod and would love to see this grow but for me I feel unable to include it in my modpack due to this persistent issue. Currently I'm using Avaritia however I much prefer the gui's and nature of this mod over it (although it is still a really awesome mod!).

I hope that this can be fixed, I feel like it is most likely to do with an event so what I will do, is I'll upload my log so you should have all the information you need.

Thanks in advance!
[latest.log](https://github.com/BlakeBr0/ExtendedCrafting/files/1830439/latest.log)

**Comment by BlakeBr0** [comment]
Is the lag reproducible with just extended crafting installed? Or in a different modpack?

**Comment by CJMinecraft01** [comment]
I'll have a look. It does seem to happen every time I have Extended Crafting installed but I'll get a couple of logs to prove it. Thanks for looking into this :+1:

**Comment by CJMinecraft01** [comment]
Ok, so under some more investigation. I've discovered that it might not just be Extended Crafting. I've just done a test with and without Extended Crafting and there is no noticeable difference. I'm still testing at the moment, but it might not just be this mod. I'm going to check this out further. I'm currently testing testing removing another mod to see if this makes a dramatic difference, but altogether it is hard to pin point the source of this lag.

**Comment by CJMinecraft01** [comment]
I've just done a test and Extended Crafting doesn't seem to be the issue, the error is still persistent when I remove another mod but the lag is more rare when this other mod is not installed so I'll look at it.

Thanks for all the help, sorry for the false alarm! :sob:
