### ISSUE TITLE
Shapeless recipe icon doesn't display in JEI

### ISSUE THREAD

**Issue by WithersChat** [BlakeBr0/ExtendedCrafting#190]
**Describe the bug**
Shapeless recipe icon doesn't display in JEI, even though the "required table tier" icon is offset to match.
Caused by that part of the code simply not existing.

**To Reproduce**
- Create a shapeless recipe
- View it in JEI

**Expected behavior**
An icon with two crossing arrows should appear in a corner of the recipe box.

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.2.21 (should be in any 1.20.1 version)
 - Cucumber: 7.0.8 (should be in any 1.20.1 version)
 - Extended Crafting: 6.0.7
 - Singleplayer or Multiplayer: Both

**Addenum**
I have made [my own fork of ExtendedCrafting](https://github.com/Monifactory/ExtendedCrafting) for 1.20.1, in which I fixed the bug along with other changes. I am willing to PR all of part of the features from my fork into the main mod, depending on interest.

**Comment by BlakeBr0** [comment]
It seems to appear properly for the ultimate singularity recipe for me. The `builder.setShapeless()` calls should already be handling this.

![image](https://github.com/user-attachments/assets/c6ee77b1-9b7a-4fdb-b65e-45e035da7d83)

**Comment by WithersChat** [comment]
Interesting. The bug might come from something else on my side then.
