### ISSUE TITLE
[Suggestion] Configurable Auto Table speed

### ISSUE THREAD

**Issue by WithersChat** [BlakeBr0/ExtendedCrafting#191]
**IMPORTANT: Feature requests will only be added to the latest supported Minecraft version.**

**Is your feature request related to a problem? Please describe.**
Auto ExtendedCrafting Tables are extremely slow, which makes them often a major bottleneck in many packs. 

**Describe the solution you'd like**
Adding configuration options for the time a Table takes to perform a recipe, as well as removing the one-item-per-tick import limit.

**Addenum**
I have made [my own fork of ExtendedCrafting](https://github.com/Monifactory/ExtendedCrafting) for 1.20.1, in which I implemented that feature along with other changes. I am willing to PR all of part of the features from my fork into the main mod, depending on interest.

**Comment by Xplodin** [comment]
> **IMPORTANT: Feature requests will only be added to the latest supported Minecraft version.**
> 
> **Is your feature request related to a problem? Please describe.** Auto ExtendedCrafting Tables are extremely slow, which makes them often a major bottleneck in many packs.
> 
> **Describe the solution you'd like** Adding configuration options for the time a Table takes to perform a recipe, as well as removing the one-item-per-tick import limit.
> 
> **Addenum** I have made [my own fork of ExtendedCrafting](https://github.com/Monifactory/ExtendedCrafting) for 1.20.1, in which I implemented that feature along with other changes. I am willing to PR all of part of the features from my fork into the main mod, depending on interest.

pleeeease pr that. Im in dire need of this feature
