### ISSUE TITLE
[Suggestion] A 5th tier of table using Netherite from newer versions

### ISSUE THREAD

**Issue by WithersChat** [BlakeBr0/ExtendedCrafting#192]
**IMPORTANT: Feature requests will only be added to the latest supported Minecraft version.**

1.16 added Netherite as a new tier of material, and having a 5th table tier with a 11x11 grid to match would make sense.

**Addenum**
I have made [my own fork of ExtendedCrafting](https://github.com/Monifactory/ExtendedCrafting) for 1.20.1, in which I implemented that feature along with other changes. I am willing to PR all of part of the features from my fork into the main mod, depending on interest.
![2024-08-10_07 49 54](https://github.com/user-attachments/assets/14c187b0-bffd-431b-a59b-3f0d24628f7b)

**Comment by BlakeBr0** [comment]
Honestly I think this would be better suited for an addon. 

The 9x9 grid is already cutting it close on larger GUI scales (I haven't looked at your impl so maybe you found a solution for that). I  don't really think there needs to be a tier above 'Ultimate'.

**Comment by WithersChat** [comment]
Alright. Just wanted to make sure I wasn't doing something separately that could be merged into the base mod.

(GUI scale is an issue, that I am still pondering how to tackle. It is low priority tho.)
