### ISSUE TITLE
Custom recipes dont appear on a server

### ISSUE THREAD

**Issue by ArtOfLuxis** [BlakeBr0/ExtendedCrafting#193]
**Describe the bug**
Creating recipes with CraftTweaker works fine, but if i try to check the recipes using JEI in multiplayer, it doesnt show any recipes on custom crafting tables and the quantum compressor

**To Reproduce**
i dont really know, i just made some recipes and it doesnt show them in JEI in multiplayer, even though they appear in singleplayer (crafttweaker log is clean, checked multiple times, thats why i think the problem is with this mod)

**Expected behavior**
custom recipes are supposed to be in JEI

**Screenshots / Scripts / Logs**
[extended.txt](https://github.com/user-attachments/files/16610044/extended.txt)
(changed to .txt so github would accept it)

**Versions (please complete the following information):**
 - Minecraft: 1.12.2
 - Forge: 14.23.5.2589
 - Cucumber: 1.12.2-1.1.3
 - Extended Crafting: 1.12.2-1.5.6
 - CraftTweaker: 1.12-4.1.20.700
 - JEI: 1.12.2-4.16.1.1012
 - Singleplayer or Multiplayer: multiplayer

**Comment by ArtOfLuxis** [comment]
updated with script

**Comment by WithersChat** [comment]
The problem is probably not with the mod, considering that dozens of packs have been using it and it worked just fine.

**Comment by BlakeBr0** [comment]
Have you figured out what the problem is? I'm not really sure what the issue could be without any logs.

**Comment by ArtOfLuxis** [comment]
I think i checked all logs and they were all clear, and the issue has not been resolved

**Comment by BlakeBr0** [comment]
Honestly not sure what the issue could be. I would be surprised if it's something on my end as I haven't touched the 1.12 version in years and there hasn't been other reports of something like this since then.

I can't remember if recipes were synced from the server in 1.12, maybe the scripts differ between the client and server?

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
