### ISSUE TITLE
KubeJS Recipe additions

### ISSUE THREAD

**Issue by KingSkel** [BlakeBr0/ExtendedCrafting#197]
Good Morning/Evening!
I'm attempting to add some recipes for some custom Quantum Compression recipes. Though it seems while the 3x3, 5x5, 7x7, and 9x9 crafting template works, the Quantum Compressing template from https://blakesmods.com/docs/extendedcrafting/compression-recipes is not working for the versions listed below.

Here is an example, of what I'm trying to do with minecraft:diamond as a placeholder until I can make sure the rest of it works:
`ServerEvents.recipes(event => {
  event.custom(
    {
      "type": "extendedcrafting:compressor",
      "power_cost": 500000,
      "ingredient": {
        "item": "#c:ingots/bronze",
        "count": 100000
      },
      "catalyst": {
        "item": "extendedcrafting:ultimate_catalyst"
      },
      "result": {
        "id": "minecraft:diamond"
      }
    }
  )
})`

I know modded materials are having a bug where the singularities are uncraftable, but until you can fix that, I need to add my own recipes. Either way, I still need this recipe to work for singularities you do not have in your mod. ie:allthemodium singularity, titanium singularity, chromium singularity, etc.

**Versions:**
 - Minecraft: 1.21.1
 - NeoForge: 21.1.61
 - Cucumber: 1.21.1-8.0.6
 - Extended Crafting: 1.21.1-7.0.0
 - KubeJS: 2101.7.0-build.171

**Comment by BlakeBr0** [comment]
Your ingredient is using the wrong syntax. It should be `{ "item": "<item id here>", "count": 100000 }` or since it looks like you want to use  a tag it should be `{ "tag": "c:ingots/bronze", "count": 100000 }`

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
