### ISSUE TITLE
Pre 1.14 code

### ISSUE THREAD

**Issue by 0xC4DE** [BlakeBr0/ExtendedCrafting#198]
I'm currently trying to work with Extended Auto to make a specific integration with AE2 Extended Life. I noticed that the earliest available branch in this repo is indeed 1.14.

am I right in assuming this commit is the latest 1.12.2 version? https://github.com/BlakeBr0/ExtendedCrafting/commit/23aff6854343b47c17fc77a261634b793c6cf26f

I was just hoping it'd be possible to have you guys make a tag or branch or w/e so that future people can reference it. If not feel free to just close this!

**Comment by BlakeBr0** [comment]
I must have deleted it by accident at some point. Should be back here now: https://github.com/BlakeBr0/ExtendedCrafting/commits/1.12/
