### ISSUE TITLE
9x9 Crafting Table not Working

### ISSUE THREAD

**Issue by Boolyman** [BlakeBr0/ExtendedCrafting#21]
I am setting up some 9x9 crafting recipes.  They show up fine in JEI but when I place the items on the crafting table, there is no output.  I have attached a video of the issue, and the syntax is below.   
https://youtu.be/0jpyYdfDmmA

`mods.extendedcrafting.TableCrafting.addShaped(<variedcommodities:orb:5>, [[<wizardry:pearl_holder>, <ore:logWood>, <ore:logWood>, <ore:logWood>, <ore:blockQuartz>, <ore:logWood>, <ore:logWood>, <ore:logWood>, <wizardry:pearl_holder>, <ore:logWood>, <wizardry:wisdom_wood_planks>, <wizardry:wisdom_wood_planks>, <wizardry:wisdom_wood_planks>, <ore:blockQuartz>, <wizardry:wisdom_wood_planks>, <wizardry:wisdom_wood_planks>, <wizardry:wisdom_wood_planks>, <ore:logWood>, <ore:logWood>, <wizardry:wisdom_wood_planks>, <wizardry:wisdom_wood_pigmented_planks>, <wizardry:wisdom_wood_pigmented_planks>, <ore:blockQuartz>, <wizardry:wisdom_wood_pigmented_planks>, <wizardry:wisdom_wood_pigmented_planks>, <wizardry:wisdom_wood_planks>, <ore:logWood>, <ore:logWood>, <wizardry:wisdom_wood_planks>, <wizardry:wisdom_wood_pigmented_planks>, <wizardry:wisdom_wood_planks>, <ore:blockQuartz>, <wizardry:wisdom_wood_planks>, <wizardry:wisdom_wood_pigmented_planks>, <wizardry:wisdom_wood_planks>, <ore:logWood>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <wizardry:crafting_plate>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:blockQuartz>, <ore:logWood>, <wizardry:wisdom_wood_planks>, <wizardry:wisdom_wood_pigmented_planks>, <wizardry:wisdom_wood_planks>, <ore:blockQuartz>, <wizardry:wisdom_wood_planks>, <wizardry:wisdom_wood_pigmented_planks>, <wizardry:wisdom_wood_planks>, <ore:logWood>, <ore:logWood>, <wizardry:wisdom_wood_planks>, <wizardry:wisdom_wood_pigmented_planks>, <wizardry:wisdom_wood_pigmented_planks>, <ore:blockQuartz>, <wizardry:wisdom_wood_pigmented_planks>, <wizardry:wisdom_wood_pigmented_planks>, <wizardry:wisdom_wood_planks>, <ore:logWood>, <ore:logWood>, <wizardry:wisdom_wood_planks>, <wizardry:wisdom_wood_planks>, <wizardry:wisdom_wood_planks>, <ore:blockQuartz>, <wizardry:wisdom_wood_planks>, <wizardry:wisdom_wood_planks>, <wizardry:wisdom_wood_planks>, <ore:logWood>, <wizardry:pearl_holder>, <ore:logWood>, <ore:logWood>, <ore:logWood>, <ore:blockQuartz>, <ore:logWood>, <ore:logWood>, <ore:logWood>, <wizardry:pearl_holder>]]);`

**Comment by BlakeBr0** [comment]
From that script it looks like you are trying to add a shaped recipe with a shapeless item array.

**Comment by Boolyman** [comment]
Ah, you are right.  I did leave a comment on your modpage asking how to toggle the recipe maker wand from shapeless to shaped, since it's nowhere to be found on your wiki.

**Comment by BlakeBr0** [comment]
I might change it to a toggle, since that would be a little more convenient as well.
