### ISSUE TITLE
the crafting is not removed

### ISSUE THREAD

**Issue by HurtsAsHell** [BlakeBr0/ExtendedCrafting#23]
Imgur[https://imgur.com/a/aRF4b](url)
This is the command [https://pastebin.com/7jQAcf7x](url)

**Comment by BlakeBr0** [comment]
You should be removing from the CompressionCrafting registry, not TableCrafting.

**Comment by HurtsAsHell** [comment]
okay; thanks,it was late and I had not seen; I'm sorry for the inconvenience and the useless iusses
