### ISSUE TITLE
BQM not detecting crafting.

### ISSUE THREAD

**Issue by Bullorg74** [BlakeBr0/ExtendedCrafting#24]
I'm guessing its a BQM issue that nothing I craft in extended crafting crafting tables register as a crafting task?

Forge 14.23.2.2654
Extended Crafting 1.12-1.3.0

**Comment by BlakeBr0** [comment]
Crafting tasks are for vanilla recipes. I can't really think of a reason to ever use a crafting task over a detection task anyways.

**Comment by Bullorg74** [comment]
Ok TY. Well I want the player to make it not find it. Anyway GREAT mod TY again.

**Comment by BlakeBr0** [comment]
I'll probably be able to make them work, not 100% sure though.
