### ISSUE TITLE
[Request] Recipes Stages support or game stages integration

### ISSUE THREAD

**Issue by Fireztonez** [BlakeBr0/ExtendedCrafting#29]
Hello,
I want to know if you can add a way to stage Extended Crafting table recipes. In the modpack I made I have a lot of idea for recipes I can made with your crafting tables, but the fact that it is not possible to assign a step that I must really pay attention to, not to make accessible certain items / blocks before the right step. Either by making more complicated the recipes, either by staging completely the table. In addition, I think is limits enormously the possibilities that I have, with the recipes of your crafting tables.

So, I wonder, is it possible for you to add an compatibility or integration of Game Stages into your mod?

Fireztonez

**Comment by Fireztonez** [comment]
Glad to see you consider my queries and think about an integration for Recipes Stages.
![4](https://user-images.githubusercontent.com/19277301/39986910-1ecc4882-5731-11e8-8641-cbc5cafe0e21.png)

**Comment by BlakeBr0** [comment]
As I just missed the 2 year anniversary of this request, I must sadly resign to the fact that I will not be implementing this. I also don't find the overhead of implementing support for this worth it for how niche it would end up being.

**Comment by dkmk100** [comment]
I think it would be used a fair amount

**Comment by dkmk100** [comment]
please add this
