### ISSUE TITLE
Anything with NBT data will not craft via combining.

### ISSUE THREAD

**Issue by scalda** [BlakeBr0/ExtendedCrafting#30]
Hi, after you fixed the issue with the combination crafting due to the mod not honouring the NBT data. 
The mod now no longer allows crafting with any items that have nbt data within the craft tweaker scripts.

MC version 1.12.2
mod version extendedcrafting-1.12-1.3.4.jar
CraftTweaker2-1.12-4.1.8

this script works
`<extendedcrafting:singularity_ultimate>, <extendedcrafting:table_ultimate>, <wct:infinity_booster_card>, <extendedcrafting:storage:4>, <appliedenergistics2:material:47>, <megaloot:upgradecharm_epic>, <megaloot:upgradecharm_rare>, <statues:blockshulkerstatue>, <statues:blockguardianstatue>, <statues:blockendermanstatue>, <enderio:block_enderman_skull:2>, <rebornstorage:storagepart:3>, <thaumcraft:curiosity_band>, <botania:pinkinator>]);`

And this one with items that have NBT doesn't work
`mods.extendedcrafting.CombinationCrafting.addRecipe(<projecte:condenser_mk1>, 50000000, <equivalentenergistics:emc_storage_component:7>, [<ironchest:iron_shulker_box_purple:2>, <extendedcrafting:storage:6>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:table_ultimate>, <wct:infinity_booster_card>, <extendedcrafting:storage:4>, <thermalexpansion:cell>.withTag({Energy: 50000000, Level: 4}), <appliedenergistics2:material:47>, <megaloot:upgradecharm_epic>, <megaloot:upgradecharm_rare>, <statues:blockshulkerstatue>, <statues:blockguardianstatue>, <statues:blockendermanstatue>, <enderio:block_enderman_skull:2>, <thermalexpansion:tank>.withTag({Fluid: {FluidName: "empoweredoil", Amount: 500000}, Level: 4}), <rebornstorage:storagepart:3>, <thaumcraft:curiosity_band>, <botania:pinkinator>]);`

Any help would be great

**Comment by BlakeBr0** [comment]
Are you sure all the tags are correct? Prior to the fix it would just ignore them entirely.

Just tested and everything seems to work properly for me.

**Comment by scalda** [comment]
All the recipes for the combination crafting that contain nbt tags for
items. If I remove the items/nbt then it will craft

**Comment by BlakeBr0** [comment]
Don't really know what to tell you since it works for me sadly

**Comment by BlakeBr0** [comment]
It's important to note that the tags need to be exactly the same, i did an TE energy cell with the tag {Recv: 25000, RSControl: 0 as byte, Facing: 3 as byte, Creative: 0 as byte, Energy: 25675000, Level: 4 as byte, SideCache: [2, 1, 1, 1, 1, 1] as byte[] as byte[], Send: 25000} and it only accepted things with that exact tag. 

In your recipe it looks like you have a lot less tag info, which could make it not work since I dont think thats a valid tag.

**Comment by scalda** [comment]
I originally had what you had above and that still didn't work. That is why
I cut out all the stuff that I did not need with in the cell to match other
wise trying to gallet a energy cell with the exact configuration that is
need by the script would be extremely differcult without understanding the
zenscript file and what each tag ment

**Comment by BlakeBr0** [comment]
Unfortunately it requires the exact tag for the inputs. Differentiating blocks with nbt like that does generally cause an issue with these kind of things sadly.
