### ISSUE TITLE
crafting tables not working well with nbt data

### ISSUE THREAD

**Issue by TheNimbleNinja** [BlakeBr0/ExtendedCrafting#32]
i made a ton of recipes in the extended crafting tables. i wanted to have the fully powered blocks/items be needed to craft a specific item. it worked in a way... the recipe would accept any powered item/block it didnt matter if it was empty, full or partial full. here is the script i made for this said process.
https://gist.github.com/TheNimbleNinja/4fcd6031010060eca7346a9aaaf3f011

**Comment by IcedReaper** [comment]
Hi,
Sorry to necro this thread, but I'd like to ask if this feature is planned to be integrated or not.
Some of the recipes I created in my Modpack to be created in the ExtendedCrafting Table rely on being NBT-Specific.
The recipe shown in JEI is the correct one with the correct items with their correct NBT-Tag, but the recipe itself ignores NBT-Data.

Thanks for letting me know.

**Comment by TheNimbleNinja** [comment]
are the tables still ignoring nbt data?

**Comment by IcedReaper** [comment]
Sadly, yes (with the version 1.5.0 for 1.12.2)

Neutrol Fluid Cell should be required:
https://imgur.com/XlC1Gvz

But empty or water cells are excepted too.
https://imgur.com/pBLwmIS
https://imgur.com/qdeYsES

**Comment by Pival81** [comment]
This is still the case, with the Ender Crafter:

//Universal remote recipe
recipes.remove(<universalremote:item_universal_remote>);
var enderium_plate = <tconstruct:large_plate>.withTag({Material:"enderium"});
mods.extendedcrafting.EnderCrafting.addShaped(<universalremote:item_universal_remote>, [
	[enderium_plate, <calculator:calculatorscreen>, enderium_plate], 
	[<ae2wtlib:infinity_booster_card>, <avaritia:resource:5>, <ae2wtlib:infinity_booster_card>], 
	[enderium_plate, <ore:circuitUltimate>, enderium_plate]
]);

![2018-12-24_20 14 39](https://user-images.githubusercontent.com/15673222/50405747-636ddf80-07b9-11e9-8329-0adbbb630a48.png)

![2018-12-24_20 14 53](https://user-images.githubusercontent.com/15673222/50405749-65d03980-07b9-11e9-94cb-e8facb1fd426.png)
