### ISSUE TITLE
Ender Crafter/Alternator Speed

### ISSUE THREAD

**Issue by TheMabinogi** [BlakeBr0/ExtendedCrafting#33]
After doing some testing ingame it seems additional Ender Alternators have very little impact on crafting speed.

Crafting an Ender Star takes ~30 seconds with 1 Ender Alternator
Crafting an Ender Star takes ~25 seconds with 40 Ender Alternators

Unless I'm doing something wrong there seems like little reason to craft additional alternators currently.

It would be nice if it worked similar to the original QED, with 40 Alternators increasing the speed 40x.

**Comment by BlakeBr0** [comment]
In the next version:
- Ender crafting will take 60 seconds each craft by default
- Each alternator will increase the speed by 1% (.6 seconds/12 ticks) by default
- 100 alternators will get to max speed by default
- The amount of time each craft takes and the effectiveness of alternators will have config options

These changes should hopefully encourage people to use more alternators.

**Comment by Itszipzon** [comment]
do they have to connect with the ender crafter?
