### ISSUE TITLE
NBT Issues, Combiner

### ISSUE THREAD

**Issue by NillerMedDild** [BlakeBr0/ExtendedCrafting#34]
Related to #30 

Hey! Would it be possible for the Combiner to take any NBT data on an item again, possibly by supplying a boolean with the recipe? I'm unable to provide some exact NBT tags to recipes, as they vary for the items I want to use.

**Comment by BlakeBr0** [comment]
This should be the case again in the next version.

**Comment by NillerMedDild** [comment]
Thank you!

**Comment by BlakeBr0** [comment]
I'm not entirely sure what your issue is then.
