### ISSUE TITLE
Automation Interface crafts only one output for recipes that have 1+ outputs

### ISSUE THREAD

**Issue by Vyraal1** [BlakeBr0/ExtendedCrafting#36]
Was making a recipe that creates 9x Ultimate Stew in Enigmatica 2 Expert, and wanted to use the automation interface. 

However in this video (https://streamable.com/75mu8) I can craft the recipe and get 9x just fine, but when using the automation interface, the output seems to be only 1x, there should at least be 2 stacks or so in the crate, and nothing else was extracting from the crate.

**Comment by BlakeBr0** [comment]
Yikers thats a nice oversight right there
