### ISSUE TITLE
Speed of Quantum Compressor

### ISSUE THREAD

**Issue by Zer0Lyfe** [BlakeBr0/ExtendedCrafting#4]
Hello, Blakebr0
I was wondering if you could you make it so that it can consume more items/t than it does now? (_like in Avaritia_)
I think it takes a really long time to make just one singularity even if you have the items in a constant flow. If you could do this I would appreciate it.

**Comment by BlakeBr0** [comment]
I made it so now by default it consumes 4 items/t. I also added a config option for it, so it can be as fast as you want.

**Comment by Zer0Lyfe** [comment]
thank you!, Blake
