### ISSUE TITLE
Automation Interface Duplication

### ISSUE THREAD

**Issue by NillerMedDild** [BlakeBr0/ExtendedCrafting#45]
Hey, one of my users just reported a strange issue with the Automation Interface - I'll just link to the issue, I hope that's alright:

https://github.com/NillerMedDild/Enigmatica2Expert/issues/180

**Comment by UltimateEnforcer** [comment]
Hey, even after replacing the automation interface, putting the recipy in again, etc., it started creating ingots out of thin air again today. I do not know what is triggering it. Again, looking inside the automation interface stopped the process of extra ingots being created.
![schermafdruk 2018-08-07 15 33 35](https://user-images.githubusercontent.com/41302254/43779089-bb6c2b76-9a57-11e8-81cb-beb1bbb5899f.png)
![schermafdruk 2018-08-07 15 33 38](https://user-images.githubusercontent.com/41302254/43779098-c2b6fe60-9a57-11e8-9e34-7d7f7cbd6ed9.png)

**Comment by UltimateEnforcer** [comment]
Possibly, the server should restart every night, and it does seem to occur only once per day. I just restarted the server manually however, and I have not seen any duplication as of yet.
