### ISSUE TITLE
More of a question then a bug

### ISSUE THREAD

**Issue by TacticalUniverse** [BlakeBr0/ExtendedCrafting#46]
Any chance you could tell me maybe why inside the Ultimate Crafting Table it overlaps the JEI Search when center bar is active.

Example 
![2018-08-20_13 24 59](https://user-images.githubusercontent.com/37633323/44359091-7889d900-a47c-11e8-8451-f6fd4e22e123.png)

**Comment by BlakeBr0** [comment]
Your GUI scale is too large
