### ISSUE TITLE
RF-based counterpart to Ender Crafter (Assembly Table + Laser workalike?)

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [BlakeBr0/ExtendedCrafting#49]
Hey! I've been playing some older modpacks again recently and I _unlike others_ actually really liked how the BC Assembly Table and Lasers were used in packs like FTB Infinity Evolved Expert Mode Skyblock to create a dynamic RF-based crafting system which would progressively get easier the more lasers a player added to their table.

Now, I know Buildcraft, albeit in Alpha, already has a few builds for MC 1.12 and that it includes the Assembly Table again, but I was still sort of wondering whether something similar to it wouldn't be a nice addition to Extended Crafting, as it's already sort of similar to the Ender Crafter's + Alternator's general method of acceleration, except that in this new mechanic, the Alternators (or whatever they would be called then) would use FE energy to process the item instead of reducing the amount of ticks it takes to craft instead.

A system like this could combine both the expandability of an Ender Crafter with the FE-based crafting mechanism of Combination Crafting and could even be expanded further to feature things like multiple tiers of Assembly Cores (I'm bad at name suggestions, I know), mandatory minimum amounts of Accelerators per recipe, higher-tier accelerators which would provide more power at once to the core, et cetera et cetera.

I know that again, this suggestion is **very** similar to a BC Assembly Table and that I shouldn't be asking for a thing that technically, to an extent, already exists (even if it's still without CT support or a stable power system for now), but I still hope you take this into consideration as I think it could be a great addition to the mod especially with the introduction of multiple tiers and such.

**Comment by brachy84** [comment]
This is waht i want
