### ISSUE TITLE
Right-Clicking a Quantum Compressor with a Crescent Hammer deletes all items inside the Compressor.

### ISSUE THREAD

**Issue by Electrolyte220** [BlakeBr0/ExtendedCrafting#50]
After accidentally right-clicking a compressor in my survival world, I found this bug:

ExtendedCrafting-1.4.3
Forge-2751

**Steps to reproduce**:
Put a catalyst and items into correct slots,
Right click the compressor with the crescent hammer,
Lose the catalyst and ALL stored items.

Clicking eject after right-clicking with the wrench does not output any items.

See below:
![Alt Text](https://gyazo.com/811fca5e68ead37b4d442433d486f466.gif)

**Comment by BlakeBr0** [comment]
I'm going to just disable this interaction in the next update. Maybe later I can implement it correctly.
