### ISSUE TITLE
Automation Interfaces with multiple recipes.

### ISSUE THREAD

**Issue by Yusunoha** [BlakeBr0/ExtendedCrafting#59]
I have a feeling that this may have already been suggested, or perhaps it's already in the works, but would it be possible for the automation interface to have more than 1 recipe?

Currently it seems that the automation interface can only hold 1 recipe, which is a real shame. Seeing as this mod is often used in end-game crafting for modpacks, it gets pretty expensive to build mulitple tables and crafting cores for all the different recipes, so it'd be nice if the AI could hold more than 1 recipe.

Ofcourse more recipes in the AI could be for a price, perhaps you need to apply upgrades to the AI before you can save multiple recipes, or add blocks on the side of the AI to enable more recipes.

**Comment by Tehelee** [comment]
I'm currently working on a fork to add jei recipe integration for the interfaces. Afterwards I'd like to take a look at what can be done to extend or integrate ae2 better.
