### ISSUE TITLE
Request for compatibility: crafttweaker 

### ISSUE THREAD

**Issue by kragnoth** [BlakeBr0/ExtendedCrafting#61]
Could you implement support for .reuse() and the other functionality that allows re-using crafting ingredients?

https://github.com/CraftTweaker/CraftTweaker/blob/1.12/CraftTweaker2-MC1120-Main/src/main/java/crafttweaker/mc1120/recipes/MCRecipeShaped.java

**Comment by Fireztonez** [comment]
Yes I agree this will, be really usefull, and I want to be able to use the `.noReturn()` and `.transformReplace(<minecraft:potato>)` and `.giveBack()` from the same section into the Crafttweaker Wiki:
https://crafttweaker.readthedocs.io/en/latest/#Vanilla/Variable_Types/IIngredient/

Thank's

**Comment by Fireztonez** [comment]
@BlakeBr0 I whant to know if you have plan to add compatibility for that soon in ExtendedCrafting, this will be really usefull for my modpack if you does!

Thank's for the Extended Crafting, this is a really great mod and very useful!!

**Comment by Cazadorsniper** [comment]
Will this issue be worked on? What I need is the noReturn() tag to work in Extended Crafting.
