### ISSUE TITLE
Extended Crafting Smart Insert

### ISSUE THREAD

**Issue by ghost** [BlakeBr0/ExtendedCrafting#66]
Hello, so today i was using the Automation Interface with a ultimate bench, but noticed that smart insert would still insert items into the interface if they were items that belonged in the recipe, but it wouldn't check if it could go in. This would be a problem if you were trying to insert more than 1 stack of 1 item in. Since it is an item that can go in, but there is no more room for the item, you have to cycle it back out.
It would be very helpful if you could fix this with smart insert.
Thanks.

**Comment by BlakeBr0** [comment]
Smart insert is for the Auto Insert functionality of the interface. Are you using that in this case?
