### ISSUE TITLE
Tranform damage recipes on Basic Crafting Table bring items to negative damage value

### ISSUE THREAD

**Issue by Fireztonez** [BlakeBr0/ExtendedCrafting#68]
Hello,
I have get a bug how can sincerly caused big advancements issue in somes case, with recipes with a default Transform Damage for an item (Like the Essence infusion recipes from Mystical Agriculture with Basic Infusion Crystal...).

On a regular crafting table, the infusion crystal get damage and, when the durability is at 0, the item break, but, with the Basic Crafting Table from Extended Crafting, the item is damage and when the durability is at 0, it will go to -1, -2.... So you can really easy have unlimited durability, if you only used that on the Basic Crafting Table.

Personnally, I think, the best way to fix that issue, is to add a real support for Crafttweaker IIgreadient Transform Damage and give back, question to fix at the same time that issue and the https://github.com/BlakeBr0/ExtendedCrafting/issues/61

Version:
Minecraft: 1.12.2
Forge: 14.23.5.2831
Extended Crafting 1.5.4
Cucumber Lib: 1.1.3
Crafttweaker: 4.1.17

**Comment by Cazadorsniper** [comment]
What is the progress on this issue?
