### ISSUE TITLE
[Question] How to create crafting with item with stay in table?

### ISSUE THREAD

**Issue by PanSzelescik** [BlakeBr0/ExtendedCrafting#71]
Using .reuse() in CraftTweaker not working, and I have this:
![image](https://user-images.githubusercontent.com/26679785/62882233-bc32be00-bd31-11e9-975a-2b7b28eb3b93.png)

I am using latest versions from CurseForge

**Comment by MaerkR** [comment]
use .transformDamage(0) instead
