### ISSUE TITLE
Basic Crafting Table - Middle Slot Issue

### ISSUE THREAD

**Issue by iKhatEX** [BlakeBr0/ExtendedCrafting#75]
Issue: Basic Crafting Table middle slot forces an output of the item in the middle.
How to reproduce:
1: Place a Basic Crafting Table
2: Place any item in the middle slot of the crafting grid

Mod Version: 1.5.4 (Persists in 1.5.5)
Minecraft Version: 1.12.2
Pack Version: Tales of the Botanist - InDev - 1.0.4
-------------------------------
[Note]: Though this issue seems minor on the mod's end; however, it's major when creating custom recipes through this mod. I hope this can be resolved.

**Comment by BlakeBr0** [comment]
I'm not sure what you mean by this. I can put items into the middle slot just fine and nothing out of the ordinary seems to happen.

**Comment by Zerrox0** [comment]
I'm having the same issue. Since you couldn't reproduce it, maybe it is some weird incompatibility with another mod?
