### ISSUE TITLE
Liquid crafting removes the item completely from the recipe

### ISSUE THREAD

**Issue by Wxrlds** [BlakeBr0/ExtendedCrafting#77]
When using `<liquid:water>*1000` in a script as ingredient, what normaly happens is, it tells you it requires any container holding 1000mb water.
![grafik](https://user-images.githubusercontent.com/42120270/64905984-416a1380-d6e0-11e9-8347-f5e7f9da8a1f.png)
The issue occurs when using `<liquid:water>*1000` in one of the Crafting Tables added by your mod. The container holding the fluid disappears from the recipe but what should happen is telling you the same as in a normal crafting table.

**Comment by BlakeBr0** [comment]
I will be closing this issue as I am no longer maintaining the 1.12 version.
