### ISSUE TITLE
Recipes Function integration

### ISSUE THREAD

**Issue by galyfray** [BlakeBr0/ExtendedCrafting#79]
can you add the integration of the recipes functions like we have with vanilla crafting table ?
https://docs.blamejared.com/1.12/en/#Vanilla/Recipes/Crafting/Recipe_Functions/

this functionallity is very usefull for making special recipes with NBT ^^

**Comment by BlakeBr0** [comment]
Sorry for the late reply: 

As I don't plan to support the 1.12 version much longer, and hate making crafttweaker stuff work, I won't be adding this.
