### ISSUE TITLE
[Request] Larger JEI Combination Crafting

### ISSUE THREAD

**Issue by NillerMedDild** [BlakeBr0/ExtendedCrafting#8]
Hey!

I'd like to request a change to the JEI integration of the Combination Crafting - Currently it's very hard to make out which ingredients are needed, when there a lot of ingredients:

![billede](https://user-images.githubusercontent.com/21295394/32272457-6deb88e0-befe-11e7-9db6-b7564226641a.png)

**Comment by BlakeBr0** [comment]
Finally got around to releasing a version with this. Hopefully its a little better than it was before.

**Comment by NillerMedDild** [comment]
Thank you! :)
