### ISSUE TITLE
Recipe maker issue

### ISSUE THREAD

**Issue by hjae78** [BlakeBr0/ExtendedCrafting#80]
When using the recipe maker to copy a recipe from a table and one or more of the items has an NBT tag like, for example, 35 as a short it's copied as '35s'. Crafttweaker requires it to be '35 as short'. It's a minor issue and only causes slight inconveniences but I'm sure it would be an easy fix and save many pack developers having to restart the game because they forgot to fix the script.

**Comment by hjae78** [comment]
After comparing the code that the recipe maker does to the code that the crafttweaker command /ct hand does I literally can not tell why this is different. The ct hand command outputs NBT tags in the '35 as short' format while the recipe maker gives '35s' but as far as I can tell they both use exactly the same methods.
[Here](https://github.com/BlakeBr0/ExtendedCrafting/blob/master/src/main/java/com/blakebr0/extendedcrafting/item/ItemRecipeMaker.java) on line 219 the tag should be in the 'as short' format. I'm really not sure what's going on here.

**Comment by Wxrlds** [comment]
Are you using the newest version? Because apparently this has been fixed in [version 1.5.6](https://www.curseforge.com/minecraft/mc-mods/extended-crafting/files/2777071) and see issue [https://github.com/BlakeBr0/ExtendedCrafting/issues/67](https://github.com/BlakeBr0/ExtendedCrafting/issues/67)

**Comment by hjae78** [comment]
You're absolutely right, I was on 1.5.5, quite stupid of me not to check that.
