### ISSUE TITLE
Automation and recipes that use buckets

### ISSUE THREAD

**Issue by ray73864** [BlakeBr0/ExtendedCrafting#82]
Playing the Dungeons, Dragons, and Space Shuttles modpack, and a lot of the recipes have things like buckets of fluid in them.

So i'm trying to automate the making of heat conductors for the Reborn Storage mod, the recipe calls for 8 iron bars, 8 silicon plates, 4 lava bricks, 2 gold coils, 2 silicon, and 1 bucket of lava.

I have the recipe set up in Refined Storage for it, I have a Refined Storage attached to a chest, I have the chest on top of the EC Automation Interface and the Automation  Interface on top of the Advanced Crafting Table.

When I request that RS makes a heat conductor, it correctly puts all the items into the chest and then the automation interface sucks them out and puts them into the correct table slots.

I have 2 issues, 1 I know is with ExtendedCrafting, the other could be but might not be.

RS has been told that 2 heat conductors are made from the recipe, all the ingredients are given to the automation interface, but the advanced crafting table only makes 1 heat conductor instead of 2.

The recipe leaves behind an empty bucket, I have tried all the options on the automation interface (smart insert, and auto-insert), but I can't get the empty bucket out of the table, so when I ask RS to make some more heat exchangers, the automation interface puts all the items in the correct spot but can't put the lava bucket into the correct spot because an empty bucket currently occupies it.

Is there any way to get the empty bucket out so that the table is empty ready for the next auto-craft?

**Comment by ecatherman** [comment]
I also have this issue.

I found an old post that references this issue but the solution listed does not make sense:
https://www.reddit.com/r/feedthebeast/comments/autfa4/e2es_extended_crafting_with_bucket_recipe/

**Comment by EpicAwesomenessTNTCreeper** [comment]
You could use XNet cables to take items out of the Extended Crafting Table.

**Comment by BlakeBr0** [comment]
I am going to be closing this as I am no longer maintaining the 1.12 version.
