### ISSUE TITLE
Custom Singularities with Craftweaker

### ISSUE THREAD

**Issue by Cazadorsniper** [BlakeBr0/ExtendedCrafting#83]
Mod version: 1.5.6
Minecraft version: 1.12.2
Pack: Project Ozone 3

I made 49 custom singularities and if I try to adjust the recipes for them using crafttweaker, the singularities become "Dummy Singularities" instead of removing said recipe and adding it back with different items to make them.

**Comment by BlakeBr0** [comment]
I am going to be closing this as I am no longer maintaining the 1.12 version.
