### ISSUE TITLE
Recipe isn't working

### ISSUE THREAD

**Issue by Boolyman** [BlakeBr0/ExtendedCrafting#84]
I am using the following recipe:

https://pastebin.com/C3DSTC3

It is not crafting, and I am not exactly sure why.   Here is the config file:

https://pastebin.com/xSkcdbED

Minecraft: 1.12.2
Cucumber Library: 1.1.3
Extended Crafting: 1.5.6

**Comment by BlakeBr0** [comment]
I'm going to be closing this as I am no longer maintaining the 1.12 version.
