### ISSUE TITLE
Quantum Compressor locks input to first input item

### ISSUE THREAD

**Issue by 04Slash** [BlakeBr0/ExtendedCrafting#85]
If you place any item into the main slot of the Quantum Compressor, it will lock the compressor to only accept that item, even if it does not convert into a singularity.
Steps to reproduce:
1. Place Quantum Compressor
2. Place Ultimate Catalyst (or any item) into the main input slot, not the catalyst slot
3. Move the catalyst into the catalyst slot
4. Place iron (or any singularity item) into the main slot

The iron will not be consumed by the quantum compressor at this point.  To fix this, you must break the quantum compressor and ensure that you do not place anything but the item you wish to turn into a singularity into the main slot. It does not matter if you place the catalyst into the catalyst slot first, or the item into the main input slot first. Is this intended mechanics?

**Comment by BlakeBr0** [comment]
This issue is fixed in version 2.0.0. Unfortunately I have no plans to update version 1 any further.
