### ISSUE TITLE
[SUGGESTION] upward compatibility for crafting tables

### ISSUE THREAD

**Issue by TheUntamed** [BlakeBr0/ExtendedCrafting#86]
It would be cool if a smaller recipe could be crafted in a larger crafting table. So that all recipes made for crafting table X can also be crafted in crafting table X+.

Just like a vanilla 2x2 crafting recipe can also be crafted in a 3x3 crafting grid.

**Comment by BlakeBr0** [comment]
This is already the case if you dont provide a required tier for the recipe. (or put 0  for the tier)
