### ISSUE TITLE
[1.15.2] Custom Recipe JSONs

### ISSUE THREAD

**Issue by curlywaffles** [BlakeBr0/ExtendedCrafting#88]
In the config file I see where the singularities are but what do the folders need to be named for the other JSONs? For the Combination, Table, Compression, and Ender Crafting?

This is just a test JSON I'm trying to use to figure this all out:
![image](https://user-images.githubusercontent.com/58758245/78459790-29a8ab80-7681-11ea-86df-5b120c0e41ca.png)

**Comment by BlakeBr0** [comment]
Goes in the recipes folder in your datapack, see https://mods.blakebr0.com/docs/extendedcrafting/table-recipes

**Comment by curlywaffles** [comment]
Ah thank you, still learning this data pack stuff.
