### ISSUE TITLE
extended crafting tables not accepting recipes from crafttweaker in 1.15.2

### ISSUE THREAD

**Issue by MercilessArchitect** [BlakeBr0/ExtendedCrafting#89]
been trying to make an expert themed pack using your mod and crafttweaker recipe adding, and it refuses to run the scripts. the coding works, im running it as said on your wiki.

**Comment by BlakeBr0** [comment]
I dont use crafttweaker anymore. You add recipes using datapacks w/ json files in 1.15. See https://mods.blakebr0.com/docs/extendedcrafting

**Comment by PyroFlareX** [comment]
Can crafttweaker support still be added though, with a mode for the wand to go along with it? It is still useful, and many don't want to deal with datapacks, and rather would use global *.zs scripts.
