### ISSUE TITLE
[1.15.2] Missing Singularities

### ISSUE THREAD

**Issue by realTIMematrix** [BlakeBr0/ExtendedCrafting#90]
Hi,

I'm using:

Minecraft: 1.15.2
Forge: 31.1.43
ExtendedCrafting: 2.0.0
Mekanism: 9.9.18
Chem Lib: 1.15.2-3

Issue:

Some of the singularities (Aluminium, Copper, Tin) that uses the "ITEM TAG" don't work at all. Only if you define the correct "ITEM" e.g "mekanism:ingot_copper" it works. 

I checked the ingots from mekanism and chemlib and both have the forge:ingots_xxxx TAG for example. But none of them appears in the compression recipes.

For me it seems that the recipes for the singularities with "tag" doesn't work

**Comment by BlakeBr0** [comment]
Which version of cucumber are you using? Did you specify the item you want to use for the tag in the cucumber-tags.json file? See https://mods.blakebr0.com/docs/cucumber/tags-config

**Comment by realTIMematrix** [comment]
I'm using cucumber 3.0.5 and i don't know that there is a file to specify the tags. This works now.

Have a last question. Is there a way to specify multiple items to one tag (see also the osmium below)? I changed the script to:

`{
"forge:ingots/osmium": [ "chemlib:ingot_osmium", "mekanism:ingot_osmium" ],
"forge:ingots/iron": "null"
}` 

but the game crashed and I don't know why. Is there no way to set up multiple items to one tag?

**Comment by BlakeBr0** [comment]
You cant have multiple output items, so no.

**Comment by realTIMematrix** [comment]
Thank you for your answer 😀
