### ISSUE TITLE
[1.15.2] upward compatibility - JEI's auto fill button

### ISSUE THREAD

**Issue by TheUntamed** [BlakeBr0/ExtendedCrafting#92]
A while ago I posted this issue: https://github.com/BlakeBr0/ExtendedCrafting/issues/86
and now I remember why I thought it's not possible.
If you want to craft a recipe in a higher tier crafting table JEI dosn't apply the grid-auto-fill button (the `+` that automatically inserts all items into the grid if existing in the inventory or shows which items are missing if not all needed items are in the inventory).

Not sure if that has to be fixed on your side or on JEI's side.

**Comment by BlakeBr0** [comment]
For this to work I would have to add the recipes to every valid table's category, which would be a mess.

**Comment by TheUntamed** [comment]
Understandable. But the way it is right now it is impossible to use a recipe that is larger than 3x3 in an even larger crafting table.

**Comment by vizthex123** [comment]
Yeah, it'd be nice. You've got to add the recipes to each table rn, which is quite annoying.
