### ISSUE TITLE
CraftTweaker Support

### ISSUE THREAD

**Issue by PyroFlareX** [BlakeBr0/ExtendedCrafting#93]
Please re add craft tweaker support.

As a modpack maker, datapacks are so annoying and buggy to use. Twice already while testing I had to redo the pack due to their bugs. I implore you to either return to craft tweaker or have dual support on 1.15.2 for it. Otherwise, I will not be able to use this mod, and its great systems in my packs. Thank you.

**Comment by PyroFlareX** [comment]
Just hook the IRecipes into vanilla and it’ll work. That is all. Please, for the hopes and dreams of all modpack makers!

**Comment by kindlich** [comment]
To add on to what PyroFlareX wrote, some more information on hist statement:

CraftTweaker has (limited) support for sending Jsons to Serializers natively.

However, for that to work, it checks the RecipeType registry and expects a RecipeType whose Resource Location also points to a RecipeSerializer.
That recipeType would also be used in removing recipes from within CrT.

So all you'd need to do is register RecipeTypes with the _same resource location as your serializers_.
Then people could at least write themselves functions to create functions that create the datapacks.


However, CrT support within the mod itself will always have more possibilities.

**Comment by Smaltin** [comment]
It's easier to have all the recipes in CraftTweaker than using both CraftTweaker and a data pack. The data packs are per-world, so it makes things more difficult. Please add CraftTweaker support to 1.15.2.

**Comment by LONGACAT** [comment]
CraftTweaker is really easy to use, which cannot be said about datapacks (not a modpack maker, made only a couple packs for private use). Also, like the comment above me says, it's easier to have everything in CraftTweaker than having in both CraftTweaker and datapacks. Please add CraftTweaker support.

**Comment by PyroFlareX** [comment]
I have successfully been able to create a fork of this mod that is compatible with CraftTweaker. Once I iron out some bugs and do a few things, I will put it up on my Github, and Curseforge possibly/probably. I will not close this issue yet. If BlakeBr0 wants me to submit a PR for it, reply here.

**Comment by BlakeBr0** [comment]
I'd appreciate a PR

**Comment by BlakeBr0** [comment]
This was added in version 2.0.1.
Docs: https://mods.blakebr0.com/docs/extendedcrafting/crafttweaker/table-recipes
