### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by LDS-XiaoYe** [BlakeBr0/ExtendedCrafting#94]
Please see it in this video.
https://c-t.work/s/9560f74e5e6f43

if this site is unavailable,please tell me and i will reupload

**Comment by BlakeBr0** [comment]
If this was for 1.15, I would appreciate a youtube link, and an explaination, maybe even some version numbers.

**Comment by LDS-XiaoYe** [comment]
1.12.2

**Comment by BlakeBr0** [comment]
I am no longer maintaining the 1.12.2 version.
