### ISSUE TITLE
[1.15.2] Server crash

### ISSUE THREAD

**Issue by BedrockLegends** [BlakeBr0/ExtendedCrafting#95]
[crash-2020-05-01_05.20.15-server.txt](https://github.com/BlakeBr0/ExtendedCrafting/files/4565870/crash-2020-05-01_05.20.15-server.txt)

**Comment by BlakeBr0** [comment]
This crash is weird. I don't think it was actually caused by any of my mods though. Something must have errored prior preventing anything from my blocks being registered.
