### ISSUE TITLE
[1.12.2] Automation interfaces only makes 1 item with recipies that are supposed to output 2.

### ISSUE THREAD

**Issue by TSideScripting** [BlakeBr0/ExtendedCrafting#97]
I am playing on a modpack with one 5x5 recipies outputting 2 items. Manually inputting the items in an advanced crafting grid allows me to correctly take the 2 items out of the output slot. However when attempting to autocraft them using Automation Interfaces, they only out 1 item. I suspect this is due to the item not normally being able to stack with one another. The item in question is Mekanism's Quantum Entengloporter.

![1 output](https://user-images.githubusercontent.com/28244401/81009065-d6767400-8e4b-11ea-8e11-758944ab3adb.png)
![2 output](https://user-images.githubusercontent.com/28244401/81009069-d70f0a80-8e4b-11ea-8abc-d90ebaa745af.png)

**Comment by BlakeBr0** [comment]
I must say it's very interesting that I didn't get a bug report for this back when I was still maintaining the 1.12 version. Unfortunately I am no longer maintaining the 1.12 version so this will have to be considered a feature.
